### PR TITLE
Onboarding: Don't show skip link if no plugins exist to skip

### LINKED ISSUE #3469: Onboarding: Start step shows skip plugins message without plugins
**Describe the bug**
When both Jetpack and WCS are already installed and Jetpack is connected, the skip option is still shown without any plugin names.

**To Reproduce**

1. Install WCS and Jetpack.
2. Connect Jetpack.
3. Visit the start step of the profiler. (You may need to delete `wc_connect_options` to visit this step)
4. Note the skip message beneath the card.

**Expected behavior**
Expected no message to be shown and for the primary button to skip to the store detail step of the profiler.

**Screenshots**
Screen Shot 2019-12-23 at 5 00 19 PM

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #3469

Removes a partial text string "Proceed without" when no plugins need to be installed.

### Screenshots
Screen Shot 2019-12-26 at 3 52 11 PM

### Detailed test instructions:

1. Delete WCS and/or Jetpack.
2. Go to the profile wizard first step and continue to install WCS and Jetpack.
3. Connect Jetpack.
4. Delete `wc_connect_options` from `wp_options`.
5. Revisit the first step and make sure the skip link is not shown.

### CODE REVIEW

File: client/dashboard/profile-wizard/steps/start/index.js [hunk 1]
```diff
@@ -269,15 +269,17 @@ class Start extends Component {
...
-				<p>
-					<Button
-						isLink
-						className="woocommerce-profile-wizard__skip"
-						onClick={ () => this.setState( { showUsageModal: true, continueAction: 'skip' } ) }
-					>
-						{ sprintf( __( 'Proceed without %s', 'woocommerce-admin' ), pluginNamesString ) }
-					</Button>
-				</p>
+				{ pluginNamesString && (
```
Comment (timmyc) [inline client/dashboard/profile-wizard/steps/start/index.js]: Minor but would it be easier to read this if we checked to see if `pluginsToInstall` size was !== 0? Only reason I mention it is I had to go back and look at the code above to see how `pluginNamesString` was being defined.

Comment (joshuatf) [reply client/dashboard/profile-wizard/steps/start/index.js]: Agreed; that's a bit more readable.  Updated in https://github.com/woocommerce/woocommerce-admin/pull/3485/commits/d4aaf6c9fd6970a4647189ccadd47096e10b1b24
