### PR TITLE
#1981 Fix/1981 welcome note added

### LINKED ISSUE #1981: Inbox: Welcome to WooCommerce Admin Note
Another note, this one welcomes new installations to the WooCommerce Admin Experience.

**Note Details**

Item | Details
-----|-------
Type | Info
Title | New feature(s)
Message | Welcome to the new WooCommerce experience! In this new release you'll be able to have a glimpse of how your store is doing in the Dashboard, manage important aspects of your business (such as managing orders, stock, reviews) from anywhere in the interface, dive into your store data with a completely new Analytics section and more!
Store Type | Existing
Trigger | On plugin install
Cadence | once
CTA Label | Learn more
CTA Target | https://woocommerce.wordpress.com/ ( but will need to update when launch post is live )

### PR DESCRIPTION
**Pull request by ronakganatra9**
Fixes #1981 

As described I have added a welcome not on plugin installed hook. Let me know if you have any suggestion to improve my PR.

### Screenshots
new feature

### Detailed test instructions:

- Install WooCommerce Admin Plugin
- Check Inbox.
- You will see the new feature's note

### CODE REVIEW

File: woocommerce-admin.php [hunk 1]
```diff
@@ -214,3 +214,15 @@ function wc_admin_set_actionscheduler_store_class( $store_class ) {
...
+/*
+ *  Add Welcome message once plugin installed
+ */
+add_action( 'wc_admin_installed', 'wc_admin_add_welcome_message' );
+
+/**
+ *  Initiate a welcome note.
+ */
+function wc_admin_add_welcome_message() {
+	WC_Admin_Notes_Welcome_Message::add_welcome_note();
```
[the remark this answers is not in the document]
Comment (ronakganatra9) [reply woocommerce-admin.php]: Hi @Aljullu Thanks for guiding me here. I have added it in the wc-install file.

File: includes/notes/class-wc-admin-notes-welcome-message.php [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+		$note->set_content( __( 'Welcome to the new WooCommerce experience! In this new release you\'ll be able to have a glimpse of how your store is doing in the Dashboard, manage important aspects of your business (such as managing orders, stock, reviews) from anywhere in the interface, dive into your store data with a completely new Analytics section and more!', 'woocommerce-admin' ) );
+		$note->set_type( WC_Admin_Note::E_WC_ADMIN_NOTE_INFORMATIONAL );
+		$note->set_icon( 'info' );
+		$note->set_name( self::NOTE_NAME );
+		$note->set_content_data( (object) array() );
+		$note->set_source( 'woocommerce-admin' );
+		$note->add_action(
+			'learn-more',
+			__( 'Learn more', 'woocommerce-admin' ),
+			'	https://woocommerce.wordpress.com/'
```
[the remark this answers is not in the document]
Comment (ronakganatra9) [reply includes/notes/class-wc-admin-notes-welcome-message.php]: Hi @Aljullu , Implemented the changes. Thank you.

**Comment by ronakganatra9** [comment]
Hello @Aljullu ,

Thanks for reviewing the PR and guiding me on the code. I have committed new changes.

File: includes/notes/class-wc-admin-notes-welcome-message.php [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+ *
+ * @package WooCommerce Admin
+ */
+
+defined( 'ABSPATH' ) || exit;
+/**
+ * WC_Admin_Notes_Welcome_Message.
+ */
+class WC_Admin_Notes_Welcome_Message {
+	const NOTE_NAME = 'woocommerce-admin-welcome-note';
```
Comment (Aljullu) [inline includes/notes/class-wc-admin-notes-welcome-message.php]: Nitpicking here, but what do you think about renaming this to `wc-admin...` like in other notes.
```suggestion
	const NOTE_NAME = 'wc-admin-welcome-note';
```

File: includes/notes/class-wc-admin-notes-welcome-message.php [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+
+	/**
+	 * Creates a note for welcome message.
+	 */
+	public static function add_welcome_note() {
+
+		// First, see if we've already created this kind of note so we don't do it again.
+		$data_store = WC_Data_Store::load( 'admin-note' );
+		$note_ids   = $data_store->get_notes_with_name( self::NOTE_NAME );
+		if ( ! empty( $note_ids ) ) {
```
Comment (Aljullu) [inline includes/notes/class-wc-admin-notes-welcome-message.php]: If I'm not wrong, we have remove this check, otherwise we are never adding this note because we have previously created `WC_Admin_Notes_Historical_Data`.

File: includes/notes/class-wc-admin-notes-welcome-message.php [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+ * WC_Admin_Notes_Welcome_Message.
+ */
+class WC_Admin_Notes_Welcome_Message {
+	const NOTE_NAME = 'woocommerce-admin-welcome-note';
+
+	/**
+	 * Creates a note for welcome message.
+	 */
+	public static function add_welcome_note() {
+
```
Comment (Aljullu) [inline includes/notes/class-wc-admin-notes-welcome-message.php]: I think we should add [this check](https://github.com/woocommerce/woocommerce-admin/blob/master/includes/notes/class-wc-admin-notes-historical-data.php#L22-L25) so we make sure we don't create this note when upgrading the plugin:
```suggestion
		$is_upgrading = get_option( WC_Admin_Install::VERSION_OPTION );
		if ( $is_upgrading ) {
			return;
		}
```

File: includes/notes/class-wc-admin-notes-welcome-message.php (hunk 4 above)
Comment (ronakganatra9) [reply includes/notes/class-wc-admin-notes-welcome-message.php]: Will not it check that Note Name(which is wc-admin-welcome-note) is available? if not then and only it will add the note. But maybe it will not need because it will work on install so. removed it.

File: includes/notes/class-wc-admin-notes-welcome-message.php (hunk 5 above)
Comment (ronakganatra9) [reply includes/notes/class-wc-admin-notes-welcome-message.php]: Thanks for reminding me. I have implemented the changes and added this check.

File: includes/notes/class-wc-admin-notes-welcome-message.php (hunk 3 above)
Comment (ronakganatra9) [reply includes/notes/class-wc-admin-notes-welcome-message.php]: Yes, sure. updated it.

File: woocommerce-admin.php [hunk 6]
```diff
@@ -214,6 +214,7 @@ function wc_admin_plugins_loaded() {
 	require_once WC_ADMIN_ABSPATH . 'includes/notes/class-wc-admin-notes-historical-data.php';
 	require_once WC_ADMIN_ABSPATH . 'includes/notes/class-wc-admin-notes-order-milestones.php';
 	require_once WC_ADMIN_ABSPATH . 'includes/notes/class-wc-admin-notes-mobile-app.php';
+	require_once WC_ADMIN_ABSPATH . '/includes/notes/class-wc-admin-notes-welcome-message.php';
```
Comment (Aljullu) [inline woocommerce-admin.php]: Small change here: can you remove the leading `/`? :slightly_smiling_face: 
```suggestion
	require_once WC_ADMIN_ABSPATH . 'includes/notes/class-wc-admin-notes-welcome-message.php';
```

Comment (ronakganatra9) [reply woocommerce-admin.php]: Sorry, My mistake implemented the change.

**Comment by ronakganatra9** [comment]
Thanks @Aljullu

File: includes/notes/class-wc-admin-notes-welcome-message.php (hunk 4 above)
Comment (Aljullu) [reply includes/notes/class-wc-admin-notes-welcome-message.php]: I missed this message, my bad!  :man_facepalming:  You were absolutely right!

I just created a PR that adds this code back (#2063). Thank you for pointing this out and my apologizes for missing this message.
