### PR TITLE
Detect missed DB version number updates and fix them.

### LINKED ISSUE #5058: Infinite ALTER TABLE statements, backups breaking
**Describe the bug**

I have a site that I updated from WooCommerce 4.1.1 to 4.4.1. (Actually I have more than one, but only this one manifested the problem).

Immediately after the update (though I didn't investigate), backups began to fail (every time) due to this error:

`mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `wp_wc_category_lookup` at row: 0`

Googling indicated that this meant that something was altering the table in between the transaction lock (for the backup) being gained, and the actual dump of that table. And indeed, adding further logging showed that WooCommerce was running the following queries on every page load:

```
ALTER TABLE wp_wc_category_lookup CHANGE COLUMN `category_id` category_id BIGINT UNSIGNED NOT NULL
ALTER TABLE wp_wc_category_lookup CHANGE COLUMN `category_tree_id` category_tree_id BIGINT UNSIGNED NOT NULL
```

So, that pointed to the WooCommerce update routines. (N.B. The table had the desired definition, so the `ALTER TABLE` was a no-op).

With some logging we discovered the root cause:

1) In the database, the value of `woocommerce_admin_version` was `1.3.0` (rather than the `1.4.0` that goes with WooCommerce 4.4.1), which results in WC running the update routines.

2) But, there was a "complete" action in the action scheduler table, indicating that the action `woocommerce_run_update_callback` with argument `array('wc_admin_update_140_db_version')` had run successfully.

3) The code in WooCommerce admin will not update the database version number if 2) is the case.

Result: when loaded, WC always runs the update routines and hence the `ALTER TABLE` statements (breaking ability to backup and hurting performance), but never actually updates the database version number.

I'd say the root logic error there is that WC-Admin is using one check (does the version number in the database match our current version?) to decide whether to run the updates, but a different check (is there a completed action in the action scheduler table?) to decide whether to actually update the database version number.

I can only guess at caused the situation whereby the database version was not updated, but whereby the action was registered as having successfully run. I note that there are lots of "update DB version" methods in `includes/wc-admin-update-functions.php` for each successive version, so I suspect there was a concurrency issue: the `UPDATE` for `1.3.0` was the last SQL request to hit the DB, even after the 1.4.0 updates had been run, so `1.3.0` was the value that stuck. So presumably this can only be reproduced by updating between multiple versions when the DB server or PHP engine is experiencing load which results in concurrent/out-of-order updates.

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #5058.

This PR seeks to identify cases where for some reason (race condition / concurrency issues cited by the reported) the DB version is out-of-sync with the performed updates.

The method used to make this determination is to see if all the update callbacks have been "completed" for version numbers greater than the option value. In these cases, the option value is then updated to those versions.

With this fix In practice (and how I structured the tests), if a store has run all the update callbacks, but the option holds `1.6.0` as the value, the new detection will see that all of the `1.7.0` callbacks are complete and will update the option to `1.7.0`. The next run of the update check will see that no version callbacks remain and will update the option to `WC_ADMIN_VERSION_NUMBER`.

### Detailed test instructions:

- Check out `main`
- Force your store version option (`woocommerce_admin_version`) back to `1.6.0` or earlier.
- Verify that the option is never updated (all callbacks have completed and won't get rescheduled)
- Check out this branch
- Verify that the option gets updated to the current version number

### CODE REVIEW

File: tests/install.php [hunk 1]
```diff
@@ -49,4 +49,28 @@ public function test_create_tables() {
 			$this->assertContains( $table, $result );
 		}
 	}
+
+	/**
+	 * Test missed DB version number update.
+	 * See: https:// github.com/woocommerce/woocommerce-admin/issues/5058
+	 */
+	public function test_missed_version_number_update() {
```
Comment (louwie17) [inline tests/install.php:57]: 🎉

**Review by louwie17 — APPROVED** [review]
Tested well, on initial run of `main` the version did update, but that was because the tasks had not run yet, when updating it after it indeed never updated.

Changes look good, and thanks for adding a test to cover this 🚀
