### PR TITLE
Do not retain values when switching between rules in the DateFilter component

### LINKED ISSUE #7422: Date values are retained when switching between rules in the DateFilter component
### Describe the bug
The `DateFilter` component used in the `AdvancedFilters` component incorrectly retains values when switching between "Before/After" and "Between" rules.

### To Reproduce

- Add a "Before" date filter to the `AdvancedFilters` component.
- Modify the date value to the 1st of the current month.
- Switch the rule to "Between"
- Bug: Observe the previously set date value now appears in the second date field.
- Change the value of the first date field to the 1st of the current month and the value of the second date field to the last day of the current month.
- Click the filter button.
- Observe the query params in the address bar are correctly updated to reflect this change.
- Switch the rule back to "Before"
- Bug: Observe the previously set date value in the second "Between" field now appears as the before date field value.
- Click the filter button.
- Bug: Observe the query params in the address bar now appear as follows (URL decoded) 

```
date_before[0]=2021-07-01&date_before[1]=2021-07-27
```

Also see https://github.com/Automattic/woocommerce-payments/issues/1632

### Expected behavior
- Values are retained when switching between "Before" & "After" rules.
- Values are reset when switching to/from the "Between" rule.

### PR DESCRIPTION
**Pull request by aprea**
Fixes #7422

Also fixes https://github.com/Automattic/woocommerce-payments/issues/1632

The `DateFilter` component used in the `AdvancedFilters` component incorrectly retains values when switching between "Before/After" and "Between" rules.

This creates a few problems (see the steps to reproduce below for the bugs / undesired behavior).

This PR changes this behavior to ensure:
- Values are retained when switching between "Before" & "After" rules.
- Values are reset when switching to/from the "Between" rule. 

### Testing instructions

**Storybook**

- Run `npm run storybook`
- Visit http://localhost:6007/ in your browser
- Navigate to the `AdvancedFilters` story from the left-hand side panel
- Click the "Open canvas in new tab" button in the top right
- Add a "Before" date filter.
- Modify the date value to the 1st of the current month.
- Switch the rule to "Between"
- Observe the previously set date value was reset and the between date fields are empty.
- Change the value of the first date field to the 1st of the current month and the value of the second date field to the last day of the current month.
- Click the filter button.
- Observe the query params in the address bar are correctly updated to reflect this change.
- Switch the rule back to "Before"
- Observe the previously set date values were reset and the new "Before" date field is empty.
- Modify the date value to the 1st of the current month.
- Click the filter button.
- Observe the query params in the address bar are correctly updated to reflect this change.

**WCPay**

In `woocommerce-admin`:
- Ensure you're on the `fix/7422-date-filter-retains-values` branch.
- Run `npm run build`
- Run `./bin/make-zip.sh woocommerce-admin.zip`
- Copy `woocommerce-admin.zip`

In `woocommerce-payments`
- Unzip `woocommerce-admin.zip` into the `docker/wordpress/wp-content/plugins` directory
- Navigate to `/wp-admin/plugins.php` and activate the WooCommerce Admin plugin.
- Navigate to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions` and attempt the steps to reproduce as detailed in https://github.com/Automattic/woocommerce-payments/issues/1632

### To reproduce the bugs

Temporarily apply the changes in `packages/components/src/advanced-filters/stories/index.js` from this branch to the `main` branch for testing.

In Storybook:

- Add a "Before" date filter to the `AdvancedFilters` component.
- Modify the date value to the 1st of the current month.
- Switch the rule to "Between"
- Bug: Observe the previously set date value now appears in the second date field.
- Change the value of the first date field to the 1st of the current month and the value of the second date field to the last day of the current month.
- Click the filter button.
- Observe the query params in the address bar are correctly updated to reflect this change.
- Switch the rule back to "Before"
- Bug: Observe the previously set date value in the second "Between" field now appears as the before date field value.
- Click the filter button.
- Bug: Observe the query params in the address bar now appear as follows (URL decoded)
 
```
date_before[0]=2021-07-01&date_before[1]=2021-07-27
```

### CODE REVIEW

File: packages/components/src/advanced-filters/date-filter.js [hunk 1]
```diff
@@ -132,6 +134,34 @@ class DateFilter extends Component {
...
+				afterText: '',
+				afterError: null,
+			};
+
+			shouldResetValue = true;
+		}
+
+		this.setState( {
+			rule: newRule,
+			...( newDateState ? newDateState : {} ),
```
Comment (aprea) [inline packages/components/src/advanced-filters/date-filter.js:159]: Note to self, I could avoid this ternary operator and simply do:

```
...newDateState
```

Using the spread operator on `null` is valid, e.g.

```
{
    foo: 'bar',
    ...null
}
// {foo: "bar"}
```

**Comment by samueljseay** [comment]
@aprea Thanks for this!

A quick look at this and it looks good to me, but I'll need to test our existing usages of it just to make sure it doesn't unintentionally break anything. 

I know Its a pain but could you add a changelog entry into the packages changelog? We don't have a consolidated way to handle package and non-package changelogs right now, so you can just add the entry under Unreleased in `packages/components/CHANGELOG.md`. And you can remove the entry you added via changelogger (sorry I know the instructions are confusing right now, we could improve this).

**Comment by aprea** [comment]
Changelog entry fixed, thanks for the heads up @samueljseay

**Review by kalessil — APPROVED** [review]
Did testing following the instructions and it works as expected.
We need approval from the maintenance team though.

**Comment by kalessil** [comment]
@samueljseay : adding you a reviewer so we are getting approval from maintainers before moving forward.

**Review by naman03malhotra — COMMENTED** [review]
The changes look good to me, and work as expected 🥳, lift a comment wrt to unit tests.

However, I can't reproduce this issue: https://github.com/Automattic/woocommerce-payments/issues/1632 with storybook (on `main` branch), can you please test this with wcpay code once and see if this is fixed.

I've tested by copying the build files from node_modules of wcpay_admin to wcpay node_modules, and I can still see this issue. Maybe I am missing something? 🤔 

image

ps: somewhere the setState is being called recursively. Also, one of the checks is failing.

**Comment by aprea** [comment]
> The changes look good to me, and work as expected 🥳, lift a comment wrt to unit tests.

Woo, thanks for the review 😄

> However, I can't reproduce this issue: [Automattic/woocommerce-payments#1632](https://github.com/Automattic/woocommerce-payments/issues/1632) with storybook (on `main` branch), can you please test this with wcpay code once and see if this is fixed.
> 
> I've tested by copying the build files from node_modules of wcpay_admin to wcpay node_modules, and I can still see this issue. Maybe I am missing something? 🤔

I don't think this will work because in the wcpay local environment the `woocommerce-admin` dist files are being enqueued from the `woocommerce` plugin rather than the `woocommerce-payments` plugin.

I also tried using `npm link` but had no luck.

You can perform some testing with the following steps:

In `woocommerce-admin`:
- Ensure you're on the `fix/7422-date-filter-retains-values` branch.
- Run `npm run build`
- Run `./bin/make-zip.sh woocommerce-admin.zip`
- Copy `woocommerce-admin.zip`

In `woocommerce-payments`
- Unzip `woocommerce-admin.zip` into the `docker/wordpress/wp-content/plugins/index.php` directory
- Navigate to `/wp-admin/plugins.php` and activate the WooCommerce Admin plugin.
- Navigate to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions` and attempt the steps to reproduce as detailed in https://github.com/Automattic/woocommerce-payments/issues/1632

> ps: somewhere the setState is being called recursively.

Thanks, I'll take a look

> Also, one of the checks is failing.

This is because of the changelog, I'm a little confused about this process, I'll wait for one of the maintainers of this repo to tell me what I've done wrong here 😄

File: packages/components/src/advanced-filters/date-filter.js [hunk 2]
```diff
@@ -132,6 +134,34 @@ class DateFilter extends Component {
...
+
+			shouldResetValue = true;
+		}
+
+		this.setState( {
+			rule: newRule,
+			...newDateState,
+		} );
+
+		onFilterChange( 'rule', newRule, shouldResetValue );
```
[the remark this answers is not in the document]
Comment (aprea) [reply packages/components/src/advanced-filters/date-filter.js:162]: Tests added in b8a1ff9d6026e8e6d9b858adc6bdee0277cbdf95

**Comment by joshuatf** [comment]
> This is because of the changelog, I'm a little confused about this process, I'll wait for one of the maintainers of this repo to tell me what I've done wrong here 😄

I'll try and give this a formal review tomorrow, but no need to worry about the failing test as this has not been updated to our new flow.  We've recently started using changelogger to add entries, so you can run `npm run changelogger -- add` to add your changelog entry (just note that this will not fix that failing test 😄 )

**Comment by kalessil** [comment]
Hey @joshuatf :wave:, thanks for stepping into the review ! Any chance to review the PR today, so we could wrap it up this week?

**Comment by joshuatf** [comment]
@kalessil Sorry, my schedule has become fairly packed with release issues so I won't be able to review this week.

File: packages/components/src/advanced-filters/test/advanced-filters.test.js [hunk 3]
```diff
@@ -0,0 +1,260 @@
...
+		);
+
+		const dateFields = screen.getAllByRole( 'textbox', {
+			name: 'Choose a date',
+		} );
+
+		// The previous value should be reset when switching to/from the "Between" rule.
+		expect( dateFields[ 0 ] ).not.toHaveValue();
+		expect( dateFields[ 1 ] ).not.toHaveValue();
+	} );
```
Comment (louwie17) [inline packages/components/src/advanced-filters/test/advanced-filters.test.js:259]: Nice work on these tests 🎉

File: packages/components/src/advanced-filters/index.js [hunk 4]
```diff
@@ -117,11 +117,12 @@ class AdvancedFilters extends Component {
 		onAdvancedFilterAction( 'match', { match } );
 	}
 
-	onFilterChange( index, property, value ) {
+	onFilterChange( index, property, value, shouldResetValue = false ) {
 		const newActiveFilters = [ ...this.state.activeFilters ];
 		newActiveFilters[ index ] = {
 			...newActiveFilters[ index ],
 			[ property ]: value,
+			...( shouldResetValue === true ? { value: null } : {} ),
```
Comment (louwie17) [inline packages/components/src/advanced-filters/index.js:125]: Hmm I am not a huge fan of adding this extra parameter, the `onFilterChange` functions seems to only be used for updating the value, so adding a `shouldResetValue` for the one case where we don't update the value seems confusing.
I would be good with going to different routes for this:
- Add a separate `onRuleChange` function that handles the reset value, although this is very specific (so maybe not a great option)
- Update the `onFilterChange` function to pass in a updated filterValue object instead:
```
onFilterChange( index, updatedFilterValue ) {
  const newActiveFilters = [ ...this.state.activeFilters ];
  newActiveFilters[ index ] = {
			...newActiveFilters[ index ],
            ...updatedFilterValue
  }
 this.setState( { activeFilters: newActiveFilters } );
}
```
This way it is more explicit in the date-filter what you are doing ( updating the role and value )

**Review by louwie17 — APPROVED** [review]
This tested well, and code overall looks good, I did leave one suggestion. This would require a potential bigger refactor, so I am fine if this happens in a separate PR and we can merge this as is (unless you feel inclined to make the changes as part of this PR).

To make sure the changelog action passes, you can add `No changelog necessary as it is in the component package`. The Github action looks for the `no changelog` in the description and passes if that is present (might have to re-run the task after you updated the description).

Thanks for updating and fixing this @aprea 🎉

File: packages/components/src/advanced-filters/index.js (hunk 4 above)
Comment (aprea) [reply packages/components/src/advanced-filters/index.js:125]: Hey @louwie17, thanks for the review!

> Hmm I am not a huge fan of adding this extra parameter

I agree. I went with this approach as it was low touch and didn't require too much refactoring.

> Update the onFilterChange function to pass in a updated filterValue object ... This way it is more explicit in the date-filter what you are doing ( updating the role and value )

This is definitely a better approach but would require refactoring the existing filter components (e.g. `AttributeFilter`, `NumberFilter`, `SearchFilter`, etc.)

Ultimately, this probably isn't too difficult but given this is my first PR to this repo I didn't want to get too adventurist.

> This would require a potential bigger refactor, so I am fine if this happens in a separate PR and we can merge this as is (unless you feel inclined to make the changes as part of this PR).

Cool thanks. In that case, I might go ahead with current approach and circle back with the aim of improving this in the future. I'll create a new GitHub issue for that now.
