### PR TITLE
Onboarding: Format product count ranges numbers without decimals

### LINKED ISSUE #3312: Onboarding: Product count dropdown has decimal places
**Describe the bug**
On the Business Details step of the profiler, the product count dropdown has decimals.

**To Reproduce**

1. Go to the Business Details step of the profiler.
2. Note the decimals in the dropdown.

**Expected behavior**
Expected integers and no decimals.

**Screenshots**
Screen Shot 2019-11-27 at 9 23 24 PM

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #3312

Fixes a change to the product count formatting since `numberFormat()` now includes precision by default.

### Before
Screen Shot 2019-11-27 at 9 23 24 PM

### After
Screen Shot 2019-11-28 at 2 13 45 PM

### Detailed test instructions:

1. Open the onboarding profiler.
2. Go to the business details step.
3. Make sure dropdown numbers are formatted as expected.

### CODE REVIEW

File: client/dashboard/profile-wizard/steps/business-details.js [hunk 1]
```diff
@@ -139,18 +139,18 @@ class BusinessDetails extends Component {
 		return keys( pickBy( values ) ).filter( name => this.extensions.includes( name ) );
 	}
 
-	getNumberRangeString( min, max = false, format = numberFormat ) {
+	getNumberRangeString( min, max = false, format = formatValue ) {
 		if ( ! max ) {
 			return sprintf(
 				_x( '%s+', 'store product count or revenue', 'woocommerce-admin' ),
-				format( min )
+				format( 'number', min )
```
Comment (jeffstieler) [inline client/dashboard/profile-wizard/steps/business-details.js]: If you didn't want to change the method signature here (since that's an API change for this function) you could use `partial` to compose it with the first argument when setting the parameter default. Though.. I don't see any calls to `getNumberRangeString()` that override `format` - perhaps its unnecessary?

Comment (joshuatf) [reply client/dashboard/profile-wizard/steps/business-details.js]: Good point.  It doesn't appear to be necessary so I've removed for now (maybe something was removed where it was previously neeeded), but /cc @justinshreve just to double check where this was being used.
