### PR TITLE
restore closed overview sections before testing

### LINKED ISSUE #7574: E2E Analytics Overview tests depend on fresh install
The WooCommerce core CI pipeline runs daily smoke tests against persistent smoke test sites. The analytics overview tests fail when run multiple times against the same site due to a change in panel order. Also, if some of those tests fail on one run, some of the panels may be hidden.

`@woocommerce/e2e-utils` offers a [`IS_RETEST_MODE`](https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/utils#retries) constant that can be used to restore the overview page to its expected new install state.

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #7574

This PR revamps the analytics overview E2E tests to use an array of section titles instead of hardcoded strings throughout the test. It also restores hidden overview panels before starting the test to support re-running tests on the same host.

### Detailed test instructions:

-   Verify CI

No testing instructions needed for inclusion into WC core.

No changelog required.

### CODE REVIEW

File: packages/admin-e2e-tests/src/specs/analytics/analytics-overview.ts [hunk 1]
```diff
@@ -11,44 +11,45 @@ const testAdminAnalyticsOverview = () => {
...
 
 		beforeAll( async () => {
 			await login.login();
 			await analyticsPage.navigate();
 			await analyticsPage.isDisplayed();
+			// Restore original order to sections
+			for ( let t = 0; t < sectionTitles.length; t++ ) {
+				const visibleSections = await analyticsPage.getSectionTitles();
+				if ( visibleSections.indexOf( sectionTitles[ t ] ) < 0 ) {
+					await analyticsPage.addSection( sectionTitles[ t ] );
```
Comment (louwie17) [inline packages/admin-e2e-tests/src/specs/analytics/analytics-overview.ts:25]: I think this would be ok for now, although we should probably replace it with clearing the `dashboard_sections` in the users `woocommerce_meta` settings. I guess this could also be part of the reset functionality, I added this to the list of todo's [for the reset PR](https://github.com/woocommerce/woocommerce-admin/pull/7064#issue-651907939)

**Review by louwie17 — APPROVED** [review]
Thanks again for working on the E2E tests @rrennick, these changes look good and tested well. I just left one comment, but that can be a future change.

File: packages/admin-e2e-tests/src/specs/analytics/analytics-overview.ts (hunk 1 above)
Comment (rrennick) [reply packages/admin-e2e-tests/src/specs/analytics/analytics-overview.ts:25]: @louwie17 That sounds good. I didn't investigate further but resetting the user meta settings may be possible with the rest api - https://developer.wordpress.org/rest-api/reference/users/

Comment (louwie17) [reply packages/admin-e2e-tests/src/specs/analytics/analytics-overview.ts:25]: Yeah that's what I was thinking, and we can make use of the `HTTPClientFactory` for that. This can be merged before that though.
