### PR TITLE
Fix orders panel loading

### LINKED ISSUE #7382: Orders panel forever loading when disabling Analytics
### Describe the bug

When the analytics is disabled, the orders panel shows a loading icon forever. It does appear the actual requests 404 in the background (as it uses a Analytics endpoint I guess). The badge seems to load fine.

Related to: #7381

### To Reproduce

1. create a new WooCommerce store with the 2.5 beta
2. Create some products and a order that is processing or on-hold
3. Disable Analytics in **WooCommerce > Settings > Advanced > Features**
4. Go to **WooCommerce > Home**
5. Hide the task list and expand the Orders panel
6. Notice how it loads forever and the badge shows the correct number.

### Screenshots
Screen Shot 2021-07-20 at 2 31 17 PM

### Expected behavior
The orders panel should still load fine

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #7382 and #7381 

This fixes an issue where the orders in the homescreen panel wouldn't load in large databases, or not load when the analytics was disabled. The main change was to make use of the `wc/admin/items` store instead of the `wc/admin/reports` store.

I had to add support for querying for the customer and products data for orders.

### Screenshots

homescreen-order-panel

### Detailed test instructions:

- Create a new WooCommerce store
- Create some products and a order that is processing or on-hold
- Disable Analytics in WooCommerce > Settings > Advanced > Features
- Go to WooCommerce > Home
- Hide the task list and expand the Orders panel
- The order you created should be listed

- Install [WC Smooth generator plugin](https://github.com/woocommerce/wc-smooth-generator) and generate several products first (between 10-50 - `wp wc generate products 25` or in **Tools > Woocommerce Smooth Generator**)
- Generate quite a few orders, ~500 - `wp wc generate orders 500` (this could take a little bit and you might want to install the [Disable Emails](https://wordpress.org/plugins/disable-emails/) plugin before that)
- Go to WooCommerce > Home
- Expand the Orders panel
- The order you created should be listed (that are in processing or on-hold)

- Enable the analytics again and open the orders panel again to see if it still works well.

<!--- Please add a Changelog note

Enter a changelog note using the following CLI command `npm run changelogger -- add` and commit changes.

### CODE REVIEW

File: client/homescreen/activity-panel/orders/index.js [hunk 1]
```diff
@@ -27,254 +26,305 @@ import {
...
+	recordEvent( `activity_panel_orders_${ eventName }`, {} );
+}
 
-	renderEmptyCard() {
-		return (
-			<Fragment>
-				<ActivityCard
-					className="woocommerce-empty-activity-card"
-					title=""
-					icon=""
```
Comment (louwie17) [inline client/homescreen/activity-panel/orders/index.js:44]: Most of the changes here are converting the component to a functional component and updating the `OrdersQuery` see below.

File: client/homescreen/activity-panel/orders/index.js [hunk 2]
```diff
@@ -291,93 +341,4 @@ OrdersPanel.defaultProps = {
...
-	let orders = [];
-
-	if (
-		countUnreadOrders === null ||
-		typeof reportOrders === 'undefined' ||
-		( reportOrders.length && ! actionableOrders.length ) ||
-		isRequesting
-	) {
-		return { isRequesting: true };
-	}
```
Comment (louwie17) [inline client/homescreen/activity-panel/orders/index.js:368]: This part has all been removed in the `useSelect` above to only use the `getItems` query, making use of the `actionableOrders` query that was already happening.

File: packages/data/src/items/selectors.js [hunk 3]
```diff
@@ -1,19 +1,32 @@
...
+		return ids.reduce( ( map, id ) => {
+			map.set( id, state.data[ itemType ][ id ] );
+			return map;
+		}, new Map() );
+	},
+	( state, itemType, query ) => {
+		const resourceName = getResourceName( itemType, query );
+		return [ state.items[ resourceName ] ];
+	}
+);
```
Comment (louwie17) [inline packages/data/src/items/selectors.js:29]: Memoized this as we are creating a new array on every call. I also added a `defaultValue` (mostly for backwards compatibility).
Mostly to handle the loading state correctly and to know when it was set to an empty array or still `undefined`. Given the `isRequesting` selector had a slight delay that was noticeable in the UI.

File: src/API/Orders.php [hunk 4]
```diff
@@ -80,14 +80,77 @@ protected function prepare_objects_query( $request ) {
...
+				order_id = ( %d )
+			    AND order_itemmeta.meta_key = '_product_id'
+				AND order_itemmeta_2.meta_key = '_qty'
+			  	AND order_itemmeta_3.meta_key = '_variation_id'
+			GROUP BY product_id
+			", // phpcs:enable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
+				$order_id
+			),
+			ARRAY_A
+		);
```
Comment (louwie17) [inline src/API/Orders.php:117]: Get the products information by using the `order_itemmeta` table instead of the `wp_wc_order_product_lookup`, which doesn't rely on the scheduled actions.

File: src/API/Orders.php [hunk 5]
```diff
@@ -107,15 +170,33 @@ protected function get_formatted_item_data( $object ) {
...
+		$extra_data = array();
+		foreach ( $extra_fields as $field ) {
+			switch ( $field ) {
+				case 'customer':
+					$extra_data['customer'] = $this->get_customer_by_id( $data['customer_id'] );
+					break;
+				case 'products':
+					$extra_data['products'] = $this->get_products_by_order_id( $object->get_id() );
+					break;
+			}
```
Comment (louwie17) [inline src/API/Orders.php:188]: Add support for customer and products data, only retrieved if specifically set in `_fields: ...`

**Review by octaedro — APPROVED** [review]
Great job @louwie17! This is testing well here and the code looks good :shipit:
