### PR TITLE
Reduce order status change delay in Orders Panel.

### LINKED ISSUE #2592: Order Panel: Completed Orders Linger in List
**Describe the bug**
After marking an order as completed ( a non-actionable status ) the order is still shown in the activity panel with the old order status.

**To Reproduce**

1. Have an order that has an "actionable" status and shows up in the activity panel.
2. Edit the order to a non-actionable status, i.e. mark it as complete.
3. Note after the POST of the edit order form is completed, the order is still shown in the order activity panel
4. Navigate to the wc-admin dashboard, and the order will still be in the panel.

**Expected behavior**
Completed orders to no longer show in my activity panel

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #2592 and #2309.

This PR seeks to reduce/eliminate the delay in order status transitions manifesting in the Orders Panel.

It does so by using the core WooCommerce Orders endpoint to determine if there are actionable orders, as well as trusting the core endpoint data over the reporting table data - both endpoints are hit and the data merged, with the core endpoint overriding the reporting endpoint. This hopefully ensures that we can catch order status (and date, etc) changes in any "direction" - processing to completed, or completed to pending, etc.

Additionally, this PR removes the default date range for the `/reports/orders` endpoint (since it's not present in the core endpoint, and we need parity). This solves #2309.

### Detailed test instructions:

- Have an order that has an "actionable" status and shows up in the activity panel.
- Edit the order to a non-actionable status, i.e. mark it as complete.
- Note after the POST of the edit order form is completed, the order is no longer in the panel.
- Navigate to the wc-admin dashboard, verify the order is no longer in the panel.

### Changelog Note:

Fix: completed orders lingering in activity panel.

### CODE REVIEW

File: client/header/activity-panel/panels/orders.js [hunk 1]
```diff
@@ -265,29 +274,37 @@ export default compose(
...
-		if ( hasActionableOrders ) {
+		// Query the core Orders endpoint for the most up-to-date statuses.
+		const allOrdersQuery = {
+			page: 1,
+			per_page: QUERY_DEFAULTS.pageSize,
+			status: orderStatuses,
+		};
+		const actionableOrders = Array.from( getItems( 'orders', allOrdersQuery ).values() );
+
+		if ( hasActionableOrders && actionableOrders.length ) {
```
Comment (joshuatf) [inline client/header/activity-panel/panels/orders.js]: I'm unable to see orders here since `hasActionableOrders` is false.  I'm thinking `hasActionableOrders` might not be needed here.  Since we've already queried for `actionableOrders` we can just check its length.

On that same note, we may want to update the unread indicator to use the same test so those aren't out of sync.

File: includes/api/class-wc-admin-rest-reports-orders-controller.php [hunk 2]
```diff
@@ -385,6 +387,24 @@ public function get_collection_params() {
 			'sanitize_callback' => 'wc_string_to_bool',
 			'validate_callback' => 'rest_validate_request_arg',
 		);
+		$params['order_includes']   = array(
```
Comment (joshuatf) [inline includes/api/class-wc-admin-rest-reports-orders-controller.php]: Nice 👍  Thanks for adding these!

File: client/header/activity-panel/panels/orders.js [hunk 3]
```diff
@@ -265,29 +274,37 @@ export default compose(
 			return { orders: [], isError: true, isRequesting: false, orderStatuses };
 		}
 
-		if ( hasActionableOrders ) {
+		// Query the core Orders endpoint for the most up-to-date statuses.
+		const allOrdersQuery = {
```
Comment (joshuatf) [inline client/header/activity-panel/panels/orders.js]: Out of scope for this PR, but would be awesome if we could just return the IDs here - https://developer.wordpress.org/reference/classes/wp_query/#return-fields-parameter

File: includes/data-stores/class-wc-admin-reports-orders-data-store.php [hunk 4]
```diff
@@ -151,8 +161,8 @@ public function get_data( $query_args ) {
 			'page'             => 1,
 			'order'            => 'DESC',
 			'orderby'          => 'date_created',
-			'before'           => WC_Admin_Reports_Interval::default_before(),
-			'after'            => WC_Admin_Reports_Interval::default_after(),
+			'before'           => '',
```
Comment (joshuatf) [inline includes/data-stores/class-wc-admin-reports-orders-data-store.php]: I like the idea of removing the default date limitations.  Just want to make sure it matches up with what is done in https://github.com/woocommerce/woocommerce-admin/pull/2636.

File: client/header/activity-panel/panels/orders.js (hunk 3 above)
Comment (jeffstieler) [reply client/header/activity-panel/panels/orders.js]: Done in 7a3f4fd.

**Comment by jeffstieler** [comment]
> Also I noticed that orders seem to be in chronological order (with the oldest at top). This may be expected, but quick sanity check while we're here.

Fixed in b5a47e1.

File: client/header/activity-panel/panels/orders.js (hunk 1 above)
Comment (jeffstieler) [reply client/header/activity-panel/panels/orders.js]: Hmm.. I'm not seeing `hasActionableOrders` as `false`. It ultimate comes from the unread indicator function: https://github.com/woocommerce/woocommerce-admin/blob/71e7e5cbf46ee3ddac31452463ec527b12cbcf04/client/header/activity-panel/index.js#L148, https://github.com/woocommerce/woocommerce-admin/blob/71e7e5cbf46ee3ddac31452463ec527b12cbcf04/client/header/activity-panel/index.js#L283

File: includes/data-stores/class-wc-admin-reports-orders-data-store.php (hunk 4 above)
Comment (jeffstieler) [reply includes/data-stores/class-wc-admin-reports-orders-data-store.php]: There might be an errant change in #2636, see: https://github.com/woocommerce/woocommerce-admin/pull/2636/files#r304572283.

**Comment by jeffstieler** [comment]
I accidentally broke the "non actionable" order query - fixed in 9a0f74d. This is ready for another review.

File: includes/data-stores/class-wc-admin-reports-orders-data-store.php (hunk 4 above)
Comment (rrennick) [reply includes/data-stores/class-wc-admin-reports-orders-data-store.php]: I think this PR is going to do the trick without implementing #2636.

File: client/header/activity-panel/panels/orders.js [hunk 5]
```diff
@@ -266,28 +275,60 @@ export default compose(
 		}
 
 		if ( hasActionableOrders ) {
+			// Query the core Orders endpoint for the most up-to-date statuses.
+			const actionableOrdersQuery = {
+				page: 1,
+				per_page: QUERY_DEFAULTS.pageSize,
+				status: orderStatuses,
+				_fields: [ 'id', 'date_created_gmt', 'status' ],
```
Comment (joshuatf) [inline client/header/activity-panel/panels/orders.js]: Awesome!  Did not know the `_fields` property was an option here.

File: client/header/activity-panel/panels/orders.js [hunk 6]
```diff
@@ -266,28 +275,60 @@ export default compose(
...
+				orders = reportOrders.map( order =>
+					merge( {}, order, actionableOrdersById[ order.order_id ] || {} )
+				);
+			}
 
 			return { orders, isError, isRequesting, orderStatuses };
 		}
 
+		// Get a count of all orders for messaging purposes.
+		// @todo: add a property to wcSettings for this?
```
Comment (joshuatf) [inline client/header/activity-panel/panels/orders.js]: Minor nitpick: todos were update to format:

`@todo Thing to do.`

Comment (jeffstieler) [reply client/header/activity-panel/panels/orders.js]: Amended the last commit to fix this. Thanks.
