### PR TITLE
Category Lookup Table - Fix Category Segments

### LINKED ISSUE #1915: Category Segments: Child categories included in totals, but not segments
This is a copy/paste from https://github.com/woocommerce/woocommerce-admin/pull/1911#issuecomment-476373476.

If I compare a parent category (this happens with some, but not all), I can see the numbers don't add up:

Screen Shot 2019-03-26 at 9 21 02 AM

When, I click through on Music category to bring up the Single Category view, I can see the 35 items sold number reflected correctly

Screen Shot 2019-03-26 at 9 25 48 AM

But if I click through on "Clothing" to inspect it in Single Category view, I can now see where the original 228 figure comes from , 193 (clothing) + 35 (music) = 228.

Screen Shot 2019-03-26 at 9 28 29 AM

This leads me to believe either:

1) The chart and table values are undercounting in the original "Compare" screen and the totals are correct.

2) The totals are over counting and the chart and table values are correct.

3) There is a way we calculate products relating to categories and parent categories that is off/wierd. When comparing a parent category and its child, its possible to that a child category has more sales because we don't automatically tag a child category with its parent.

Screen Shot 2019-03-26 at 9 36 03 AM

In fact, if we drill down to view each separately, items that are found in `Clothing › Accessories` are also found in `Clothing`. And those sales are reflected in the totals, but not in the table/chart found in the Compare view. This leads me to believe 1) above is the likely scenario.

I see from @Aljullu's screenshots that he has the same issue, but @LevinMedia was not able to reproduce this issue (at least with "Clothing"). @Aljullu are you seeing something similar when drilling down into Single Category view?

Continuing, it seems like totals use `get_products_by_cat_ids` to grab all the products to look for to gather data pertaining to a category, which counts all child categories as well. But segments use another mechanism which does not.

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #1915 

Second attempt at https://github.com/woocommerce/woocommerce-admin/pull/2247 with a different lookup table structure based on @joshuatf suggestion. I'll leave https://github.com/woocommerce/woocommerce-admin/pull/2247 open until this is reviewed.

Creates a category lookup table which stores term relationships for the full category hierarchy.

The table stores data about category hierarchy; the tree and all IDs within. Storing `depth` was unfortunately not straightforward and requires lots of PHP side processing to work out depth per term. I removed that after bashing my head against the desk a few hours.

Data is synced when a category is edited (and changes), and also on install.

Stats work by joining by category_id and then grouping by the tree_id. This join appears to solve our issues in #1915.

To test:

- Update, deactivate and reactivate. Cron job will build the lookup table in short time.
- View Analytics > Categories. Check the totals look good. 
- Try example tests cases which were broken in https://github.com/woocommerce/woocommerce-admin/issues/1915. Totals should include totals from children.

### CODE REVIEW

File: includes/class-wc-admin-loader.php [hunk 1]
```diff
@@ -145,7 +163,7 @@ public static function load_features() {
 	/**
 	 * Registers a basic page handler for the app entry point.
 	 *
-	 * @todo The entry point for the embed needs moved to this class as well.
+	 * TODO: The entry point for the embed needs moved to this class as well.
```
Comment (Aljullu) [inline includes/class-wc-admin-loader.php]: In #1474 we converted all `TODO:` and similar comments to `@todo`. Any reason to change it back? :smile:

Comment (mikejolley) [reply includes/class-wc-admin-loader.php]: phpcs moans about them :)

**Comment by joshuatf** [comment]
@mikejolley Does this need another review or on hold for the time being?

File: includes/class-wc-admin-install.php [hunk 2]
```diff
@@ -265,6 +271,7 @@ public static function create_events() {
 		if ( ! wp_next_scheduled( 'wc_admin_daily' ) ) {
 			wp_schedule_event( time(), 'daily', 'wc_admin_daily' );
 		}
+		wp_schedule_single_event( time() + 10, 'generate_category_lookup_table' );
```
Comment (joshuatf) [inline includes/class-wc-admin-install.php]: I think this should probably also be run during import.  We also may want to remove any scheduled events in the `on_deactivation()` hook.

**Comment by mikejolley** [comment]
@joshuatf Feedback resolved. Is it ok to leave the sync on import in your hands?

**Comment by rrennick** [comment]
This PR is ready for re-review.

**Comment by psealock** [comment]
>Sounds good! Created a follow-up issue to tackle this here.

>I think this is good to merge once we fix failing tests. When I dump my category table during unit tests, it looks like the wc_category_lookup table is empty. Until we get the action scheduler sync in place, I think we might need to run the lookup hook on create_{$taxonomy}.

@joshuatf it seems wise to not release this until the issue you created #2765 is also included in the release. Am I reading this correctly in that we could potentially run into a scenario where the table doesn't exist but could an attempt to query could happen?

If so, we should add blocked status and tackle #2765 as soon as possible.

File: src/Loader.php [hunk 3]
```diff
@@ -473,7 +491,7 @@ public static function inject_after_notices() {
 	 * Edits Admin title based on section of wc-admin.
 	 *
 	 * @param string $admin_title Modifies admin title.
-	 * @todo Can we do some URL rewriting so we can figure out which page they are on server side?
+	 * TODO: Can we do some URL rewriting so we can figure out which page they are on server side.
```
Comment (joshuatf) [inline src/Loader.php]: Nitpick: We should change this to our standardize format of `@todo`:
```suggestion
	@todo Can we do some URL rewriting so we can figure out which page they are on server side?
```

File: src/Loader.php [hunk 4]
```diff
@@ -343,7 +361,7 @@ public static function is_admin_page() {
 	/**
 	 *  Returns true if we are on a "classic" (non JS app) powered admin page.
 	 *
-	 * @todo See usage in `admin.php`. This needs refactored and implemented properly in core.
+	 * TODO: See usage in `admin.php`. This needs refactored and implemented properly in core.
```
Comment (joshuatf) [inline src/Loader.php]: See `@todo` nitpick below.

File: tests/framework/helpers/class-wc-helper-reports.php [hunk 5]
```diff
@@ -21,5 +21,6 @@ public static function reset_stats_dbs() {
 		$wpdb->query( "DELETE FROM $wpdb->prefix" . \Automattic\WooCommerce\Admin\API\Reports\Products\DataStore::TABLE_NAME ); // @codingStandardsIgnoreLine.
 		$wpdb->query( "DELETE FROM $wpdb->prefix" . \Automattic\WooCommerce\Admin\API\Reports\Coupons\DataStore::TABLE_NAME ); // @codingStandardsIgnoreLine.
 		$wpdb->query( "DELETE FROM $wpdb->prefix" . \Automattic\WooCommerce\Admin\API\Reports\Customers\DataStore::TABLE_NAME ); // @codingStandardsIgnoreLine.
+		\Automattic\WooCommerce\Admin\CategoryLookup::instance()->regenerate();
```
Comment (joshuatf) [inline tests/framework/helpers/class-wc-helper-reports.php]: This works okay as a workaround for the tests, but I think we should still be adding entries to the lookup table when a new category is created.

When I create a new product category currently, no entry is added until I force a regeneration.

Comment (rrennick) [reply tests/framework/helpers/class-wc-helper-reports.php]: The reason I needed to add the regenerate call was that the `uncategorized` category wasn't in the lookup table. When you create a new category it is added to the table. This unit test verifies that https://github.com/woocommerce/woocommerce-admin/blob/update/category-lookup-hierarchy/tests/api/reports-categories.php#L110:L129

Comment (joshuatf) [reply tests/framework/helpers/class-wc-helper-reports.php]: Ah, that makes sense.

Since `regenerate()` looks like it's already being scheduled, should we just run all scheduled actions here instead of manually calling `regenerate()`?

Comment (rrennick) [reply tests/framework/helpers/class-wc-helper-reports.php]: > Since regenerate() looks like it's already being scheduled, should we just run all scheduled actions here instead of manually calling regenerate()?

`regenerate` is scheduled in CRON vs AS. Running the pending actions doesn't generate the table.

**Comment by rrennick** [comment]
> I think we might still want to get make sure new categories are synced with this table before merging.

That's done in https://github.com/woocommerce/woocommerce-admin/blob/update/category-lookup-hierarchy/src/CategoryLookup.php#L56

**Comment by psealock** [comment]
@rrennick @joshuatf Is https://github.com/woocommerce/woocommerce-admin/issues/2765 still needed to be resolved before merging this one? Or can that issue be folded into the sync refactor we spoke about at the GM?

**Comment by rrennick** [comment]
@psealock I think #2765 can be done separately. We discussed breaking the sync up into multiple classes. It would fit better with that.

**Comment by psealock** [comment]
Thanks @rrennick, I'll just give this a last test and look through tomorrow before approving/merging. In the meantime, I reworked https://github.com/woocommerce/woocommerce-admin/issues/2765 to reflect a broader refactor of the `ReportsSync` class.
