### PR TITLE
Check for good WC_Orders before using instance methods.

### LINKED ISSUE #1985: Fatal error if customer doesn't exist
**Describe the bug**
In processing the historical data, it aborts while importing batches. In our case, it seemed to be several orders that, for whatever reason, no longer have a customer in the system.

**To Reproduce**
Re-process historical orders with missing customers.

**Expected behavior**
The error should be handled so it does not cause a fatal error, which also seems to abort processing the rest of the items in that particular scheduled group.

One example:

Running 100 actions  36 % [=======================================>                                                                     ] 0:13 / 0:38
Started processing action 1335011
[02-Apr-2019 19:35:52 UTC] PHP Fatal error:  Uncaught Error: Call to a member function date() on null in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:477
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(407): WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order(Object(WC_Admin_Order))
#1 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(368): WC_Admin_Reports_Orders_Stats_Data_Store::update(Object(WC_Admin_Order))
#2 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(269): WC_Admin_Reports_Orders_Stats_Data_Store::sync_order(16357)
#3 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(255): WC_Admin_Reports_Sync::orders_lookup_process_order(16357)
#4 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Admin_Reports_Syn in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 477
Fatal error: Uncaught Error: Call to a member function date() on null in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:477
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(407): WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order(Object(WC_Admin_Order))
#1 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(368): WC_Admin_Reports_Orders_Stats_Data_Store::update(Object(WC_Admin_Order))
#2 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(269): WC_Admin_Reports_Orders_Stats_Data_Store::sync_order(16357)
#3 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(255): WC_Admin_Reports_Sync::orders_lookup_process_order(16357)
#4 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Admin_Reports_Syn in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 477

### PR DESCRIPTION
**Pull request by jeffstieler**
## Prevent potential get_customer_id() & other functions running into a fatal error when $order is a bool (false)

Reworking of https://github.com/woocommerce/woocommerce-admin/pull/2326 - props to @KZeni.

Fixes #1985.

Check for good `WC_Order` objects before using instance methods during sync.

### Detailed test instructions:

1. Use a dataset with Refunds where the parent Order has been deleted from the DB (like WCCOM)
1. Import All of the past data into WooCommerce Admin.
1. Verify the import doesn't have failed scheduled actions citing "PHP Fatal error Uncaught Error: Call to a member function get_customer_id() on boolean"

### Changelog Note:

Fix: PHP errors on missing refund orders during import.

### CODE REVIEW

File: tests/api/orders.php [hunk 1]
```diff
@@ -56,4 +56,30 @@ public function test_get_items_number_param() {
 		$this->assertEquals( 200, $response->get_status() );
 		$this->assertEquals( $order->get_id(), $orders[0]['id'] );
 	}
+
+	/**
+	 * Verify that deleted refund parent orders don't cause
+	 */
+	public function test_refund_parent_order_deleted() {
```
Comment (joshuatf) [inline tests/api/orders.php]: Sweet!  👍

File: includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php [hunk 2]
```diff
@@ -436,10 +436,12 @@ public static function update( $order ) {
 		);
 
 		if ( 'shop_order_refund' === $order->get_type() ) {
-			$parent_order        = wc_get_order( $order->get_parent_id() );
-			$data['customer_id'] = WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order( $parent_order );
-			$data['parent_id']   = $parent_order->get_id();
-			$format[]            = '%d';
+			$parent_order = wc_get_order( $order->get_parent_id() );
+			if ( is_a( $parent_order, 'WC_Order' ) ) {
```
Comment (joshuatf) [inline includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php]: I don't think this section will be necessary after rebase.

**Comment by jeffstieler** [comment]
> Code here looks good. I think it needs a quick rebase since I was also working on bugs here in #2418 that got merged in.

Cool, will take care of that.

> But checking if it's of type WC_Order seems like a safer way of doing this if refunds are sneaking in here.

Hm.. it wasn't my intention to screen out refunds (without looking I assumed they inherited from `WC_Order` not `WC_Abstract_Order`). I'll have to double check if that's OK to do.

File: includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php (hunk 2 above)
Comment (jeffstieler) [reply includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php]: I think that it is - there's still a chance the parent order doesn't exist.

File: tests/api/reports-customers.php [hunk 3]
```diff
@@ -418,4 +418,12 @@ public function test_customer_shipping_name() {
 		$this->assertCount( 1, $reports );
 		$this->assertEquals( 'Daenerys Targaryen', $reports[0]['name'] );
 	}
+
+	/**
+	 * Test that bad order params don't cause PHP errors when retrieving customers.
+	 */
+	public function test_customer_retrieval_from_order_bad_order() {
```
Comment (joshuatf) [inline tests/api/reports-customers.php]: ❤️
