### PR TITLE
Fix 'cannot read property' error from ExPlat

### LINKED ISSUE #7599: Fix error when retrieving woo_country_code in ExPlat
### Describe the bug

This [PR](https://github.com/woocommerce/woocommerce-admin/pull/7533) adds `woo_country_code` value from `window.wcSettings.preloadSettings.general.woocommerce_default_country`.

The change started making `Cannot read property 'general' of undefined ` error since the value is no longer accessible at `window.wcSettings.preloadSettings.general`

The value is not at `window.wcSettings.admin.preloadSettings.general.woocommerce_default_country`. Change the location to fix the error.

### To Reproduce

1. Navigate to WooCommerce -> Home
2. Open the inspector -> console. The error should be shown.

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7599 

This PR fixes `Cannot read property 'general' of undefined` error from the ExPlat package by correctly accessing `woocommerce_default_country` value.

### Detailed test instructions:

1. Checkout  this branch and run `npm start`
2. Navigate to WooCommerce -> Home
3. Open the inspector and confirm no error from the ExPlat package.

**Testing backward compatibility**

1. Open [WCAdminSharedSettings.php](https://github.com/woocommerce/woocommerce-admin/blob/main/src/WCAdminSharedSettings.php#L64) 
2. Add the following code inside the `if` statement.

```
\Automattic\WooCommerce\Blocks\Package::container()->get( \Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class )->add(
	'preloadSettings',
	function() {
		return array(
			'general' => array(
				'woocommerce_default_country' => 'test'
			)
		);
	},
	true
);			
```

3. Open the inspector and navigate to WooCommerce -> Home
4. Go to the network tab and search for `experiment`. You should see a request to the explat endpoint.
5. Confirm the `woo_country_code` value is `test`

no changelog

### CODE REVIEW

File: packages/explat/src/assignment.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export const fetchExperimentAssignment = async ( {
 		experiment_name: experimentName,
 		anon_id: anonId ?? undefined,
 		woo_country_code:
-			window.wcSettings.preloadSettings.general
+			window.wcSettings.admin.preloadSettings.general
```
Comment (adrianduffell) [inline packages/explat/src/assignment.ts:25]: I think this will need to check for both objects 😅  

I know WC Pay bundles the ExPlat package directly at the moment, so in the future I think it would need to access the value from `window.wcSettings.preloadSettings.general` in situations where newer WC Pay is installed against an older version of WooCommerce.

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Thanks @moon0326, I think this just needs a small tweak for backwards compatibility.

It will also need a changelog entry for the package so we can publish it (when publishing script works again! 😅 😅 😅 😅 )

File: packages/explat/src/assignment.ts (hunk 1 above)
Comment (moon0326) [reply packages/explat/src/assignment.ts:25]: That's a good suggestion. Thank you for catching it 👍

Comment (moon0326) [reply packages/explat/src/assignment.ts]: - Added change log in https://github.com/woocommerce/woocommerce-admin/pull/7600/commits/6b33b0361a477f5afe7a34fbd243b1752cf3331b
- Attempt to get the value in `window.wcSettings.preloadSettings.general` first in https://github.com/woocommerce/woocommerce-admin/pull/7600/commits/95243b3d162e3a38286321c34f57344fe2e1205c

I've also updated testing instructions.

**Review by adrianduffell — APPROVED** [review]
Awesome stuff, thanks @moon0326! LGTM let's ship it 🚀 

Do we need to transition to using `getSetting`? If so I'll create an issue to follow-up on later.

I get the whitescreen error below in WP 5.6 making the `WCAdminSharedSettings.php` change for testing. I think it is unrelated to this PR. Without that PHP change my country code is correct: `woo_country_code=US:CA`

Screen Shot 2021-08-31 at 11 25 04 am

Will investigate further.

**Comment by moon0326** [comment]
> Awesome stuff, thanks @moon0326! LGTM let's ship it 🚀
> 
> Do we need to transition to using `getSetting`? If so I'll create an issue to follow-up on later.
> 
> I get the whitescreen error below in WP 5.6 making the `WCAdminSharedSettings.php` change for testing. I think it is unrelated to this PR. Without that PHP change my country code is correct: `woo_country_code=US:CA`
> 
> Screen Shot 2021-08-31 at 11 25 04 am
> 
> Will investigate further.

Thank you! 

Yup, I think it would be nice if use `getSetting`. It's already a [package](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/wc-admin-settings). I think we can make the change for the next release.
