### PR TITLE
Use cron for unsnoozing admin notes

### LINKED ISSUE #3360: Pending wc_admin_unsnooze_admin_notes
**Describe the bug**
It seems like pending wc_admin_unsnooze_admin_notes are not deleted on plugin deactivate, and the job continues hourly, spitting to WP comments. I see many people also complaining about this online the past several months.

**To Reproduce**

1. Deactivate Woo
2. Deactivate Woo Admin
(not necessarily in that order)
3. Several days later find 4000+ approved comments by Author "ActionScheduler" in response to "wc_admin_unsnooze_admin_notes" in WP comments.
4. Reinstall WP. Head over to Status->Scheduled Actions to find wc_admin_unsnooze_admin_notes still pending. 
5. Delete the pending cron
6. Stop getting hourly comment "spam"

**Expected behavior**
wc_admin_unsnooze_admin_notes should be removed when Woo Admin is deactivated.

**Desktop (please complete the following information):**

* OS: Mac 10.15.1
* Browser Firefox 71

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #3360.

This PR seeks to replace the Action Scheduler based "unsnooze" functionality with a recurring WP-Cron job.

There has been a lot of confusion and backlash around the Action Scheduler implementation:

* https://github.com/woocommerce/woocommerce-admin/issues/1946
* https://github.com/woocommerce/woocommerce-admin/issues/2364
* https://github.com/woocommerce/woocommerce-admin/issues/3360
* https://github.com/woocommerce/woocommerce-admin/issues/3659

### Detailed test instructions:

- Use WP Crontrol to verify a `wc_admin_unsnooze_admin_notes` cron event exists
- Go to Tools > Scheduled Actions, verify no `wc_admin_unsnooze_admin_notes` events are pending

### Changelog Note:

Tweak: use cron instead of Action Scheduler for unsnoozing notes.

### CODE REVIEW

File: src/FeaturePlugin.php [hunk 1]
```diff
@@ -148,7 +148,7 @@ protected function define_constants() {
 		$this->define( 'WC_ADMIN_PLUGIN_FILE', WC_ADMIN_ABSPATH . 'woocommerce-admin.php' );
 		// WARNING: Do not directly edit this version number constant.
 		// It is updated as part of the prebuild process from the package.json value.
-		$this->define( 'WC_ADMIN_VERSION_NUMBER', '0.24.0' );
+		$this->define( 'WC_ADMIN_VERSION_NUMBER', '0.25.1' );
```
Comment (psealock) [inline src/FeaturePlugin.php]: You can omit this change. This and several other places get updated by `npm run pre-release`. This is why tests are failing. Perhaps just update the test instructions instead?

File: includes/wc-admin-update-functions.php [hunk 2]
```diff
@@ -61,3 +62,17 @@ function wc_admin_update_0230_rename_gross_total() {
 function wc_admin_update_0230_db_version() {
 	Installer::update_db_version( '0.23.0' );
 }
+
+/**
+ * Remove the note unsnoozing scheduled action.
+ */
+function wc_admin_update_0251_remove_unsnooze_action() {
+	wc_unschedule_action( WC_Admin_Notes::UNSNOOZE_HOOK, array(), WC_Admin_Notes::QUEUE_GROUP );
```
Comment (psealock) [inline includes/wc-admin-update-functions.php]: I'm also getting a warning here:
```
PHP Notice:  wc_unschedule_action is <strong>deprecated</strong> since version 2.1.0! Use as_unschedule_action() instead.
```

**Comment by timmyc** [comment]
Should we change the target of this branch to `version/1.0`?

**Comment by jeffstieler** [comment]
This is ready for another review.

**Comment by indianmomszurich** [comment]
Hi
We are facing this on our site.. has the fix been released? (I am not a techie, trying to find an answer)

**Comment by ecomturbo** [comment]
Same here. We have a wc_admin_unsnooze_admin_notes with empty action. What should be done please? Thank you.

**Comment by jeffstieler** [comment]
Hello @indianmomszurich @ecomturbo,

Yes, this fix was released quite some time ago. If you're up-to-date on WooCommerce and still seeing a pending`wc_admin_unsnooze_admin_notes` action in Tools > Scheduled Actions, it is safe to delete it.

Don't hesitate to create a new issue (type: bug) if you're still having problems. If you do, please be sure to include the version number of WooCommerce you're using and if you're also using the WooCommerce Admin plugin separately (with its version as well). Thanks!
