### PR TITLE
Bugfix on payments step in CBD flow

### LINKED ISSUE #4053: Payments step - CBD flow: redirect to the wrong Square page (WC-Admin 1.1 testing)
**Describe the bug**
- The "Connect" button in the Square flow for CBD stores should redirect the user to Square's attestation page: https://squareup.com/t/f_partnerships/d_referrals/p_woocommerce/c_general/o_none/l_us/dt_alldevice/pr_payments/?route=/solutions/cbd
This redirect is exclusive for the CBD flow
- The redirect should open on a new tab, so the user can keep WooCommerce opened while taking care of Square

**To Reproduce**

1. Select United States as country in the Store Details step
2. Select CBD and other hemp-derived products in the Industry step
3. Select Physical products in the Product Types step
4. Go to the Setup Payments task
5. Click "Set up" and then "Connect"
6. See the redirect to this [link](https://squareup.com/login?return_to=%2Foauth2%2Fauthorize%3Fclient_id%3Dsq0idp-wGVapF8sNt9PLrdj5znuKA%26response_type%3Dcode%26scope%3DMERCHANT_PROFILE_READ%2BPAYMENTS_READ%2BPAYMENTS_WRITE%2BORDERS_READ%2BORDERS_WRITE%2BCUSTOMERS_READ%2BCUSTOMERS_WRITE%2BSETTLEMENTS_READ%2BITEMS_READ%2BITEMS_WRITE%2BINVENTORY_READ%2BINVENTORY_WRITE%26state%3Dhttps%253A%252F%252Ftestwcadmin11.mystagingwebsite.com%252Fwp-admin%252Fadmin.php%253Fpage%253Dwc-admin%2526amp%253Btask%253Dpayments%2526amp%253Bmethod%253Dsquare%2526amp%253Bsquare-connect-finish%253D1%2526amp%253B_wpnonce%253Dda20158ef9)

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #4053

There is a bugfix and a new feature in this PR:

**In the Square flow for CBD stores**
- `Bugfix` - The `Connect` button should redirect the user to Square's attestation [page](https://squareup.com/t/f_partnerships/d_referrals/p_woocommerce/c_general/o_none/l_us/dt_alldevice/pr_payments/?route=/solutions/cbd).
- `New feature` - After pressing `Connect` a new tab opens with the Square webpage.

_In the file: `/src/API/OnboardingPlugins.php`, the `array_search` method was changed to `in_array`.
We used the method `array_search` that returns the position of the found element in the array. When the element was in the first position, the result was `0` and didn't execute the conditional statement. Now we use `in_array` instead. This method returns a boolean value._

### Detailed test instructions:
- On the 2nd step of the `Onboarding Wizard` (_Industry_) choose `CBD and other hemp-derived products`.
- The `countryCode` must be `US`
- Go to:
      `WooCommerce`|`Dashboard`|`Set up payments` (or use this URL `/wp-admin/admin.php?page=wc-admin&task=payments`)
- **Only** the `Square` payment method should be visible. The text: `Selling CBD products is only supported by Square.` should be visible in the card.
screenshot-square

- After finishing the process a new tab should be opened with the URL: 
`https://squareup.com/t/f_partnerships/d_referrals/p_woocommerce/c_general/o_none/l_us/dt_alldevice/pr_payments/?route=/solutions/cbd`. And the current tab should redirect the user to the dashboard.

_If the industry `CBD and other hemp-derived products` is not selected, the `Set up payments` should 
 have a normal behavior._

### CODE REVIEW

File: client/dashboard/task-list/tasks/payments/square.js [hunk 1]
```diff
@@ -59,6 +65,13 @@ class Square extends Component {
 		);
 
 		try {
+			let newWindow = null;
+			if ( hasCbdIndustry ) {
+				// It's necessary to declare the new tab before the async call,
+				// otherwise, it won't be possible to open it.
+				newWindow = window.open( '/', '_blank' );
+			}
```
Comment (jeffstieler) [inline client/dashboard/task-list/tasks/payments/square.js:73]: Seems like we'd want to open this flow in a new window regardless of the CBD industry? (Most other payment gateway connection are occurring in new tabs/windows)

File: client/dashboard/task-list/tasks/payments/square.js [hunk 2]
```diff
@@ -43,7 +44,12 @@ class Square extends Component {
...
-		const { createNotice, options, updateOptions } = this.props;
+		const {
+			createNotice,
+			hasCbdIndustry,
+			options,
+			updateOptions,
+		} = this.props;
 		this.setState( { isPending: true } );
 
 		updateOptions( {
```
Comment (jeffstieler) [inline client/dashboard/task-list/tasks/payments/square.js:55]: I know this is unrelated to your changes, but since this is updating the wrong setting - can you fix?

File: client/dashboard/task-list/tasks/payments/square.js (hunk 1 above)
Comment (octaedro) [reply client/dashboard/task-list/tasks/payments/square.js:73]: Hi @jeffstieler,
As I understood from this [answer](https://github.com/woocommerce/woocommerce-admin/issues/4053#issuecomment-609608685), the new tab should only be opened on the CBD industry flow, not the normal Square flow.
Do you think it should be different?

Comment (jeffstieler) [reply client/dashboard/task-list/tasks/payments/square.js:73]: I don't feel too strongly about this, but it did strike me as odd that we aren't being consistent on behavior across all payment gateway connections.

File: client/dashboard/task-list/tasks/payments/square.js (hunk 2 above)
Comment (octaedro) [reply client/dashboard/task-list/tasks/payments/square.js:55]: Hi @jeffstieler,
I fixed the issue in the commit [a8388ec](https://github.com/woocommerce/woocommerce-admin/pull/4061/commits/a8388ecc5c1ab8893508c32da580df637af769cc).

Also, there was a `validateDOMNesting` warning in the payment list (URL: `/wp-admin/admin.php?page=wc-admin&task=payments`) because we weren't adding only text inside a `p` tag. I added this change in the commit [dd22d5](https://github.com/woocommerce/woocommerce-admin/pull/4061/commits/7dd22d5676f2bec2699ba316d1db58dac3f7bcee).

Could you take a look at this change too?
