### PR TITLE
Avoid duplicate preload tags.

### LINKED ISSUE #6841: Preloaded dependencies get added multiple times
**Describe the bug**
When we have a plugin load a script which has `wc-components` as a dependency. It adds the preload link multiple times, ex:

```
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/style.css?ver=1618834704" as="style" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/style.css?ver=1618834704" as="style" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/style.css?ver=1618834704" as="style" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=1618834704" as="script" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=1618834704" as="script" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=1618834704" as="script" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1618834704" as="script" />
```

**To Reproduce**

1. Create a new plugin `npm run create-wc-extension`
2. Add `wc-components` as one of the script dependencies
3. `npm install && npm start` and activate the plugin
4. View the page source of a WooCommerce Admin pages such as Analytics > Overview
5. Notice that the preload link for `components/index.js` will be shown twice

**Expected behavior**
I'd expect the preload link to be added only once regardless of how many scripts use the same dependency.

**Additional context**
The problem comes from the way the loader loops through the dependencies and sub-dependencies, see: https://github.com/woocommerce/woocommerce-admin/blob/v2.2.0/src/Loader.php#L713-L730

The only requirement for the dependency to add a preload link is for it to be on the allowed list, it doesn't have any check to see if there was another script which already added the tag.

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #6841

### Detailed test instructions:

- Create a new plugin `npm run create-wc-extension`
- Add `wc-components` as one of the script dependencies
- `npm install && npm start` and activate the plugin
- View the page source of a WooCommerce Admin pages such as Analytics > Overview
- Verify that the preload link for `components/index.js` is not shown twice

### CODE REVIEW

File: src/Loader.php [hunk 1]
```diff
@@ -43,6 +43,16 @@ class Loader {
 	 */
 	protected static $required_capability = null;
 
+	/**
+	 * An array of dependencies that have been preloaded (to avoid duplicates).
+	 *
+	 * @var array
+	 */
+	protected $preloaded_dependencies = array(
```
Comment (joshuatf) [inline src/Loader.php:51]: Nice 👍  Seems like a reasonable way to handle this.

**Review by joshuatf — APPROVED** [review]
Code looks sound and is testing well on my end.  LGTM! 🚢
