### PR TITLE
Exclude auto-draft and trashed orders from imports.

### LINKED ISSUE #2229: Draft orders being included in import queries
**Describe the bug**

Draft orders (`shop_order` posts with a status of `auto-draft`) aren't being excluded from the import queries.

I noticed this when testing https://github.com/woocommerce/woocommerce-admin/pull/2208 - the Orders count was higher than I expected.

**To Reproduce**
Steps to reproduce the behavior: _(after #2208 is merged)_

Before testing - enable the progress bars:

> In `client/analytics/settings/historical-data/layout.js` line 70 set: const showImportStatus = true;, so progress bars are displayed.

1. Go to WooCommerce > Analytics > Settings
1. Select "Last 24 hours"
1. Make note of the orders count
1. Go to WooCommerce > Orders > Add New (this creates a draft)
1. Go back to WooCommerce > Analytics > Settings
1. Select "Last 24 hours" again
1. Verify that the Orders count has increased

**Expected behavior**

Drafts to be excluded from the import set. They aren't useful for stats.

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #2229.

Exclude `auto-draft` and `trash` status order from imports.

### Detailed test instructions:

_If you want to see this in the UI, you'll need to merge https://github.com/woocommerce/woocommerce-admin/pull/2208 as well._

Before testing - enable the progress bars:

> In `client/analytics/settings/historical-data/layout.js` line 70 set: `const showImportStatus = true;`, so progress bars are displayed.

1. Go to WooCommerce > Analytics > Settings
1. Select "Last 24 hours"
1. Make note of the orders count
1. Go to WooCommerce > Orders > Add New (this creates a draft)
1. Go back to WooCommerce > Analytics > Settings
1. Select "Last 24 hours" again
1. Verify that the Orders count remained the same

Alternatively, check the test code.

### CODE REVIEW

File: tests/api/reports-import.php [hunk 1]
```diff
@@ -320,7 +336,7 @@ public function test_import_status() {
 		);
 
 		$this->assertEquals( 200, $response->get_status() );
-		$this->assertEquals( $i, $report['orders'] );
+		$this->assertEquals( $i - 1, $report['orders'] );
```
Comment (rrennick) [inline tests/api/reports-import.php]: The `$i - 1` doesn't have any explanation for deducting the 1. This might be better with a comment or just `4` in the assertion.
