### PR TITLE
Fix warnings in report segmenting

### LINKED ISSUE #2775: Category chart re-render broken on long time scale
**Describe the bug**
Related to #1849 .

If you check out #2710 the category comparison chart renders correctly but when it re-renders after 20 minutes, it does not render correctly. This also happens if you load the chart for a single category.

Initial investigation looks like in the re-render the chart is passed a sliced array of the first 100 days + days 201+.

**To Reproduce**

1. Use `wc-smooth-generator` to generate 1000 order between Jan 1 & Jul 15
2. Use `wp action-scheduler run` to import the generated orders
3. Set default date filter to year to date
4. Go to Analytics -> Categories
5. Do a comparison report between the top two categories
6. Leave the tab in the foreground and wait for it to refresh (was 20 minutes for me)
7. See chart
8. For single category, repeat process except in step #4 click on the top category in the table

**Expected behavior**
Chart should re-render correctly.

**Screenshots**
Screen Shot 2019-08-09 at 1 17 13 PM

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #2775

This PR is a based on #2710 and fixes 4 warnings that might occur while building report segments. With WB_DEBUG enabled the warning output causes the result of the api request to be ignored.

### Detailed test instructions:

**You may need to experiment with categories to find ones that break the chart without this PR.**
1. Use `wc-smooth-generator` to generate 1000 order between Jan 1 & Jul 15
2. Use `wp action-scheduler run` to import the generated orders
3. Set default date filter to year to date
4. Go to Analytics -> Categories
5. Do a comparison report between the top two categories
6. Force a refresh of the page using the browser refresh
7. Chart should render every time
8. Verify no warnings are output to debug log during load / refresh.

### Changelog Note:

Fix: Charts being partially rendered on long time periods.

### CODE REVIEW

File: includes/class-wc-admin-reports-products-stats-segmenting.php [hunk 1]
```diff
@@ -94,8 +94,9 @@ protected function get_product_related_intervals_segments( $segmenting_selection
 		$product_segmenting_table = $wpdb->prefix . 'wc_order_product_lookup';
 
 		// LIMIT offset, rowcount needs to be updated to LIMIT offset, rowcount * max number of segments.
-		$limit_parts      = explode( ',', $intervals_query['limit'] );
-		$orig_rowcount    = intval( $limit_parts[1] );
+		$limit_parts   = explode( ',', $intervals_query['limit'] );
+		$orig_rowcount = intval( $limit_parts[1] );
+		// @todo - this is breaking intervals.
```
Comment (psealock) [inline includes/class-wc-admin-reports-products-stats-segmenting.php]: Is there an issue already for this?

**Comment by rrennick** [comment]
> Can you explain what the changes are doing?

The first commit is from https://github.com/woocommerce/woocommerce-admin/pull/2710

The second commit is for this PR https://github.com/woocommerce/woocommerce-admin/pull/2776/commits/0cdf15e04cd29274a529b98311399a73e3b61706 . The data being passed to the segment functions includes data for categories that are not included in the comparision (which produces the warning).

**Comment by rrennick** [comment]
Confirming this PR fixes the issue noted in https://github.com/woocommerce/woocommerce-admin/issues/2775#issuecomment-520822756

Screen Shot 2019-08-13 at 10 43 15 AM

**Comment by jeffstieler** [comment]
I've updated https://github.com/woocommerce/woocommerce-admin/pull/2710 to keep the `LIMIT` clause, so this PR will need to be updated.

Additionally, I've found the culprit for the render issue and probably the missing segment IDs that this PR quiets down. Inbound PR soon.

**Comment by rrennick** [comment]
Merge conflict on this one has been fixed. #2710 needs to be merged first.

**Comment by jeffstieler** [comment]
Now that #2710 is merged, lets drop 4129ec0af0d7d458316057e200fe765382f5963f from this PR.

**Comment by rrennick** [comment]
> Now that #2710 is merged, lets drop 4129ec0 from this PR.

done.
