### PR TITLE
OBW: respect Store Location async

### LINKED ISSUE #4031: Clicking continue on set store location task list step triggers console error
**Describe the bug**

Working through the onboarding task list when I click the "Continue" button on the "Set Store Location Step" I get the following console errors on master.

Production Build:

> TypeError: i is not a function

Development Build:

> TypeError: updateSettings is not a function

**Expected behavior**
I continue to the next step.

**Screenshots**

Screen Shot 2020-03-31 at 8 18 02 pm

**Desktop (please complete the following information):**

* OS: macOS
* Browser firefox dev edition
* Version 5.0b10
* WooCommerce 4.0.1

I had a look to see if this was a dupe but couldn't see anything - apologies if it is known.

### PR DESCRIPTION
**Pull request by psealock**
Fixes #4031

1. `<StoreLocation />` had the wrong props for updating locations in the shipping task.
2. Async methods in the shipping and tax tasks called actual async actions after the settings refactor. This caused duplicate logic to be called:

>Functions of the OBW were written using async/await pattern even though data actions weren't actually async functions. This was a known problem #2959. Async functions called by StoreLocation's onComplete called duplicate logic also found in its parent component's componentDidUpdate. But, since the async logic was called synchronously, one or the other wasn't actually firing.

>Settings data stores were refactored and did export async action creators. So that duplicate logic ended up being fired twice.

### Detailed test instructions:

1. Go through both “Set up shipping” and “Set up tax” tasks on the Dashboard.
2. Delete the `woocommerce_store_address` option and go through each again.
3. Try a variety of jetpack connected and not installed on each.
4. Make sure no steps are skipped and the tasks operate as they should.

### CODE REVIEW

File: client/dashboard/task-list/tasks/tax.js [hunk 1]
```diff
@@ -58,42 +61,53 @@ class Tax extends Component {
 		this.setState( this.initialState );
 	}
 
-	componentDidUpdate( prevProps ) {
+	shouldShowSuccessScreen() {
```
Comment (joshuatf) [inline client/dashboard/task-list/tasks/tax.js:64]: Nice!  I like the addition of this method.

File: client/dashboard/task-list/tasks/tax.js [hunk 2]
```diff
@@ -58,42 +61,53 @@ class Tax extends Component {
...
+		const { stepIndex } = this.state;
+		const currentStep = this.getSteps()[ stepIndex ];
+		const currentStepKey = currentStep && currentStep.key;
+
+		// If general settings have stopped requesting, check if we should show success screen.
+		if (
+			prevProps.isGeneralSettingsRequesting &&
+			! isGeneralSettingsRequesting
+		) {
+			if ( this.shouldShowSuccessScreen() ) {
```
Comment (joshuatf) [inline client/dashboard/task-list/tasks/tax.js:105]: Now that you've simplified the logic a bit, could we remove this block and setting the `step` to `null` in favor of just checking `this. shouldShowSuccessScreen()` in the render method?

File: client/dashboard/task-list/tasks/tax.js [hunk 3]
```diff
@@ -58,42 +61,53 @@ class Tax extends Component {
...
+			isGeneralSettingsRequesting,
+		} = this.props;
+		const { woocommerce_calc_taxes: calcTaxes } = generalSettings;
+		const { stepIndex } = this.state;
+		const currentStep = this.getSteps()[ stepIndex ];
+		const currentStepKey = currentStep && currentStep.key;
+
+		// If general settings have stopped requesting, check if we should show success screen.
+		if (
+			prevProps.isGeneralSettingsRequesting &&
```
Comment (joshuatf) [inline client/dashboard/task-list/tasks/tax.js:102]: Does `updateAndPersistSettingsForGroup` return a promise now?  Is it possible to `await` in the respective update methods?  Optionally we could handle this in a follow-up if it does.

**Comment by mattsherman** [comment]
From initial testing of this (haven't reviewed code yet)...

- The "Set store location" step in each task is not auto-skipped if the store location is already set. It shows the task with the current store location filled out.
- Clicking "Configure" button in "Configure tax rates" step results in brokenness... button stays in "busy" state and nothing happens. No errors in console.

**Comment by mattsherman** [comment]
>     * Clicking "Configure" button in "Configure tax rates" step results in brokenness... button stays in "busy" state and nothing happens. No errors in console.

I think I found the issue... I'll test a fix and push a commit to this PR's branch if it works.

**Comment by mattsherman** [comment]
>     * The "Set store location" step in each task is not auto-skipped if the store location is already set. It shows the task with the current store location filled out.

Working on a fix for this.

**Comment by mattsherman** [comment]
> > ```
> > * The "Set store location" step in each task is not auto-skipped if the store location is already set. It shows the task with the current store location filled out.
> > ```
> 
> Working on a fix for this.

@psealock I can't think of a way to fix this without refactoring the "get next step" handling as I did in #4091. But, that was a relatively big refactor. Perhaps it is best to just live with this as a known issue for 1.1 and cycle back to proper fix of this after the release (ideally, we wouldn't be calling `completeStep()` in `componentDidUpdate()`)? Or, perhaps you can think of a quick fix for this?

File: client/dashboard/task-list/tasks/tax.js (hunk 3 above)
Comment (psealock) [reply client/dashboard/task-list/tasks/tax.js:102]: It does, would address in follow up.

File: client/dashboard/task-list/tasks/tax.js (hunk 2 above)
Comment (psealock) [reply client/dashboard/task-list/tasks/tax.js:105]: Great point. I'd rather address in a follow up as I'm hesitant to fiddle with this at this stage.

**Comment by psealock** [comment]
>Perhaps it is best to just live with this as a known issue for 1.1 and cycle back to proper fix of this after the release

I think this is the best course of action. It will allow us time to fix this issue at its core: Moving as much logic as possible to an async nature and/or changing Settings data selectors to differentiate `isRequesting` in the getting context v. updating.

**Comment by psealock** [comment]
I found a bug:

If you complete the setup and have Jetpack connected, when you go to the Tax task you will see this success screen:

Screen Shot 2020-04-21 at 11 57 13 AM

If you run `wp option delete woocommerce_store_address` and redo the Tax task after a refresh, you'll get a prompt to enter address. Once you do and click "continue", the success screen should pop up. Instead it goes back to Dashboard.

Working on a fix now.

**Comment by psealock** [comment]
Fixed in https://github.com/woocommerce/woocommerce-admin/pull/4149/commits/45513cd215bcee220754ac7a3d8067028140e185

**Comment by psealock** [comment]
Tested on Ephemeral site with Jetpack connected, unconnected, with store address, and without store address on shipping and tax tasks. Working well for me.
