### PR TITLE
Orders report now shows coupons in Coupon(s) column

### LINKED ISSUE #2745: CSV Report doesn't show Coupon data
**Describe the bug**
The coupon codes used for orders are not displayed in the CSV.

**To Reproduce**

1. Go to `Orders` report
2. Click on `Download`
3. Open the CSV report
4. Coupon data in the report displayed in the Dashboard shows the coupon used but the CSV does not.

**Expected behavior**
The coupon used in the order should be shown here

**Screenshots**
Screenshot
Screenshot direct link: https://d.pr/BhDohk

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome 
* Version 75.0.3770.142 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by cojennin**
Fixes #2745

With this PR, the `Orders` report will now show coupons in the "Coupon(s)" column.

### Screenshots
Screen Shot 2019-08-19 at 12 47 26 PM
Screen Shot 2019-08-19 at 12 47 39 PM

### Detailed test instructions:

- Go to `Orders` report
- Click on `Download`
- Open the CSV report
- Coupon data in the report now displayed in Dashboard and CSV

### CODE REVIEW

File: client/analytics/report/orders/table.js [hunk 1]
```diff
@@ -192,7 +192,7 @@ export default class OrdersReportTable extends Component {
 						formattedCoupons.length ? [ formattedCoupons[ 0 ] ] : [],
 						formattedCoupons
 					),
-					value: formattedCoupons.map( item => item.code ).join( ' ' ),
+					value: formattedCoupons.map( coupon => coupon.label ).join( ' ' ),
```
Comment (joshuatf) [inline client/analytics/report/orders/table.js]: Can we comma separate these?

```suggestion
					value: formattedCoupons.map( coupon => coupon.label ).join( ', ' ),
```

Comment (cojennin) [reply client/analytics/report/orders/table.js]: Yea, for sure, I thought about doing that but the **Product** column also had them separated by spaces.
