### PR TITLE
Order milestones: prevent order count queries from being issues on every request.

### LINKED ISSUE #2222: Inbox: Repeated SQL Queries on woocommerce.com
**Describe the bug**
With v0.11 running on the dev environment of WooCommerce.com, the database server was getting exhausted with repeated slow queries for:

`SELECT COUNT( * ) FROM wp_posts WHERE post_type = ‘shop_order’ AND post_status = ‘wc-completed’`

The code was https://github.com/woocommerce/woocommerce-admin/blob/master/includes/notes/class-wc-admin-notes-order-milestones.php#L104 to `get_orders_count()` in the init method of the `milestone` class.

In order to stabilize the environment, I had to set an early `return 0` in `get_orders_count()`.

### PR DESCRIPTION
**Pull request by jeffstieler**
Refactor first two order milestones to behave the same as the others.

This PR seeks to stop order count queries from firing on every request. It does so by removing special handling for the first two order milestones (first order, first ten orders). This is a change in behavior - if a store had its first 150 orders placed within an hour, it will no longer receive three notifications. Just one for the 100 order milestone.

Fixes #2222.

### Detailed test instructions:

- Starting on a fresh store with no orders, place an order
- Trigger the `wc_admin_process_orders_milestone` cron event to run (use Crontrol to delete job)
- Verify the "first order" note is in the inbox
- Verify CTA goes to https://docs.woocommerce.com/document/managing-orders/
- Place 10 orders
- Trigger the `wc_admin_process_orders_milestone` cron event to run (use Crontrol to delete job)
- Verify the "ten orders" note is in the inbox
- Verify CTA goes to https://woocommerce.com/success-stories/
- Verify the "first order" note is no longer in inbox
- Place 100 orders (smooth generator can really help here)
- Trigger the `wc_admin_process_orders_milestone` cron event to run (use Crontrol to delete job)
- Verify the "100 orders" note is in the inbox
- Verify the "ten orders" note is no longer in inbox
- Verify CTA goes to Orders Report

### CODE REVIEW

File: includes/notes/class-wc-admin-notes-order-milestones.php [hunk 1]
```diff
@@ -230,6 +165,103 @@ public function get_current_milestone() {
...
+	/**
+	 * Get the appropriate note content for a given milestone.
+	 *
+	 * @param int $milestone Order milestone.
+	 * @return string Note content for the milestone.
+	 */
+	public function get_note_content_for_milestone( $milestone ) {
+		switch ( $milestone ) {
+			case 1:
+				return __( 'Congratulations on getting your first order from a customer! Learn how to manage your orders.', 'woocommerce-admin' );
```
Comment (mikejolley) [inline includes/notes/class-wc-admin-notes-order-milestones.php]: The last part of this note (Learn how to manage your orders) seems out of place? Any reason why this text cannot be the CTA text in `get_note_action_for_milestone`?

Comment (timmyc) [reply includes/notes/class-wc-admin-notes-order-milestones.php]: I _think_ the exact verbiage here was outlined by Pi/Marketing - but seems like a valid change.

**Comment by timmyc** [comment]
Thanks @jeffstieler
