### PR TITLE
fix: onboarding wizard checkmarks go missing sometimes

### LINKED ISSUE #8156: Setup Wizard: The "completed" icons of the steps in the progress bar get lost under certain conditions
### Description
If you fill some forms/pages of the Setup Wizard and try to go back to the initial page (Store Details) by clicking the button in the progess bar, the "completed" blue tick icons of the steps between the latest filled one and the "Store Details" one get lost in the progress bar. For instance, if you have filled the pages until the "Product Types" one and go to the "Store Details" again, the icon of the "Industry step" will get lost in the progress bar.

Note: This issue is easier to explain visually, please check the video attached.

### To Reproduce
1. Start the Setup Wizard.
2. Fill the "Store Details" and "Industry" forms and go to the "Product Types" page.
3. Click the "Store Details" button in the progress bar in order to go back to that step of the Setup Wizard.

### Actual behavior
The blue tick of the "Industry" step is missing in the progress bar.

### Video
https://user-images.githubusercontent.com/45979455/149209074-c9cf42a0-2329-4c8c-969f-042b4da0c09a.mp4

### Expected behavior
The blue tick of the "Industry" step in the progress bar should keep appearing.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits)
* WordPress 5.8.2
* WooCommerce 6.0.0
* PHP 7.4.27

### PR DESCRIPTION
**Pull request by rjchow**
- checkmarks in the stepper component go missing if the first checkmark is hidden
- happens because of html id collision between the checkmarks
- added some randomness to the mask ids

Fixes #8156 

### Detailed test instructions:

1. Start the Setup Wizard.
1. Fill the "Store Details" and "Industry" forms and go to the "Product Types" page.
1. Click the "Store Details" button in the progress bar in order to go back to that step of the Setup Wizard.

Should see that the checkmarks for "Industry" and "Product Types" render correctly

### CODE REVIEW

File: changelogs/fix-8156-obw-checkmarks-go-missing [hunk 1]
```diff
@@ -0,0 +1,6 @@
+Significance: patch
+Type: Fix
+
+Added random IDs to SVG checkmarks in stepper component #8222
```
Comment (chihsuan) [inline changelogs/fix-8156-obw-checkmarks-go-missing:4]: @rjchow Could you also add this line to `packages/components/CHANGELOG.md` under the `Unreleased`?

**Review by chihsuan — CHANGES_REQUESTED** [review]
Good job to spot this bug! 👍  Please update the component's changelog as well.

File: packages/components/src/stepper/check-icon.js [hunk 2]
```diff
@@ -3,34 +3,38 @@
...
-			id="mask0"
-			mask-type="alpha"
-			maskUnits="userSpaceOnUse"
-			x="2"
-			y="3"
-			width="14"
-			height="12"
+export default () => {
+	// we need a unique mask id because HTML ids are global in nature and collisions result in strange outcomes
+	const maskId = Math.floor( Math.random() * 10000000 );
```
Comment (chihsuan) [inline packages/components/src/stepper/check-icon.js:8]: This looks good! Another approach I'm thinking of is using a global counter as 'markID' since we don't need to worry about threads issues. However, randomness should help in some conditions.

File: changelogs/fix-8156-obw-checkmarks-go-missing (hunk 1 above)
Comment (rjchow) [reply changelogs/fix-8156-obw-checkmarks-go-missing:4]: Thanks for catching that!

File: packages/components/src/stepper/check-icon.js (hunk 2 above)
Comment (rjchow) [reply packages/components/src/stepper/check-icon.js:8]: I thought about that... but it seemed like a lot of extra complication using React context to manage this for an ID that will never be externally used. I'll add a prefix to the string though

**Review by chihsuan — APPROVED** [review]
Test well and LGTM. 👍
