### PR TITLE
Assign parent order status as children order status if refund order

### LINKED ISSUE #7197: [GlobalStep] "Return" amount is displayed as "Zero" on the Revenue report screen.
## Bug Description:
"Return" amount is displayed as "Zero" on the Revenue report if "Completed" orders are excluded from Analytics settings screen.

## Environment:
Woocommerce Version : WooCommerce 5.4.1
WordPress version: (v5.7.2)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Add some products.
1. Go to Shop page and purchase some products.
1. Go to WooCommerce->Orders.
1. Make a Refund for some orders.
1. Now go to Analytics->Revenue screen.
1. Note that Return amount is displayed.
1. Go to Analytics->Settings.
1. Select "Completed" for Excluded Statuses.
1. Click on Save settings.
1. Go to Analytics->Revenue and refresh the page.
1. Observe that "Return" amount is displayed as "Zero".

## Actual Result:
"Return" amount is displayed as "Zero" on the Revenue report screen.

## Expected Result:
"Return" amount should get updated on the Revenue report screen.

## Video:

https://user-images.githubusercontent.com/41110392/122246587-4cb92700-cee4-11eb-881f-fbb7a93a98e2.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WordPress address (URL): https://spotless-alpaca.jurassic.ninja
Site address (URL): https://spotless-alpaca.jurassic.ninja
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: ❌ 5.7.2 - There is a newer version of WordPress available (5.8-beta2-51167)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 9.76MB
Database Data Size: 7.03MB
Database Index Size: 2.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
customize_changeset: 1
mailpoet_page: 1
nav_menu_item: 5
page: 7
post: 2
product: 18
product_variation: 7
revision: 6
shop_coupon: 3
shop_order: 13
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.4.0
Facebook for WooCommerce: by Facebook – 2.6.0
Google Listings and Ads: by WooCommerce – 1.0.0
Jetpack: by Automattic – 9.8.1
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.64.0
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Shipping & Tax: by WooCommerce – 1.25.14
WooCommerce: by Automattic – 5.4.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 55
Oldest: 2021-06-16 07:24:51 +0000
Newest: 2021-06-16 14:51:37 +0000

### Status report information ###

Generated at: 2021-06-16 15:01:36 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #7197 

Assign parent order status as children order status if refund order

### Screenshots
Before
螢幕快照 2021-06-24 下午9 55 05

After
螢幕快照 2021-06-24 下午10 24 22

### Detailed test instructions:

1. Make a Refund for an order.
2. Go to WooCommerce -> Settings -> Analytics.
3.  Select "Completed" for Excluded Statuses.
4. Go to WooCommerce -> Analytics -> Revenue.
5. See summary 'Returns' item renders as expected.

### CODE REVIEW

File: src/API/Reports/Orders/Stats/DataStore.php [hunk 1]
```diff
@@ -544,7 +544,7 @@ public static function update( $order ) {
 			$parent_order = wc_get_order( $order->get_parent_id() );
 			if ( $parent_order ) {
 				$data['parent_id'] = $parent_order->get_id();
-				$format[]          = '%d';
+				$data['status']    = self::normalize_order_status( $parent_order->get_status() );
```
Comment (joshuatf) [inline src/API/Reports/Orders/Stats/DataStore.php:547]: Nice 👍

File: src/Schedulers/OrdersScheduler.php [hunk 2]
```diff
@@ -165,6 +165,12 @@ public static function import( $order_id ) {
 			CustomersDataStore::sync_order_customer( $order_id ),
 		);
 
+		$order_refunds = $order->get_refunds();
+
+		foreach ( $order_refunds as $refund ) {
```
Comment (joshuatf) [inline src/Schedulers/OrdersScheduler.php:170]: I think this loop is going to end up with some level of repeated imports.  I think this fine from a data standpoint, but will have some impact on performance.

Maybe this would even allow us to skip queueing refunds in the scheduler and simply defer to this loop to handle syncing refunds.  @jeffstieler any thoughts on this?

**Review by joshuatf — COMMENTED** [review]
Thanks for working on this, @hsingyuc!  I think this tests fairly well, but I'd like to get some feedback from others on the performance impact here.

File: src/Schedulers/OrdersScheduler.php (hunk 2 above)
Comment (jeffstieler) [reply src/Schedulers/OrdersScheduler.php:170]: Is this change required to resolve the issue?

I'm a bit hesitant to introduce this loop as it somewhat obscures the amount of work being done in each import (though it may not be much.. how many refunds can orders have?) but mostly because we already have something working.

**Review by jeffstieler — COMMENTED** [review]
Nice catch cleaning up the extra formatting token!

Is there perhaps a way to add a migration to fix the `status` column for orders that have already been imported? (It would be pretty disruptive for a large store to have to re-run the entire import porcess to fix their data) _cc: @joshuatf_

File: src/Schedulers/OrdersScheduler.php (hunk 2 above)
Comment (joshuatf) [reply src/Schedulers/OrdersScheduler.php:170]: >how many refunds can orders have?

An order can technically have an infinite amount of refunds, though we know realistically the median number of refunds is `1`.

>Is this change required to resolve the issue?

Another option would be to watch for `woocommerce_order_status_changed` and schedule all child refunds on that hook.

Though looking at what we currently import on an order, I'm wondering if `sync_refunds` is not a good way to simplify the scope of these imports and our logic around an order import.

```php
			OrdersStatsDataStore::sync_order( $order_id ),
			ProductsDataStore::sync_order_products( $order_id ),
			CouponsDataStore::sync_order_coupons( $order_id ),
			TaxesDataStore::sync_order_taxes( $order_id ),
			CustomersDataStore::sync_order_customer( $order_id ),
```

**Comment by joshuatf** [comment]
>Is there perhaps a way to add a migration to fix the status column for orders that have already been imported?

@jeffstieler Solid idea.

@hsingyuc you can find some examples of migration functions in `includes/wc-admin-update-functions.php`.  We'll need to write a SQL query that looks for rows with `parent_id` on the order stats table and updates its status based on the parent row.  Feel free to ping me if you need any help with writing this.

After writing this query, the function should be added to `src/Install.php` under `$db_updates`.

**Comment by hsingyuc** [comment]
@jeffstieler @joshuatf Thank you for the feedback! I tested the SQL query but not sure how to test the function, kindly let me know, thanks!

File: src/Schedulers/OrdersScheduler.php (hunk 2 above)
Comment (jeffstieler) [reply src/Schedulers/OrdersScheduler.php:170]: After discussing in Slack, I believe that the potential impact from this loop is likely far less than the existing sync logic (namely `sync_order_products`). Let's :shipit:

**Review by jeffstieler — APPROVED** [review]

**Comment by ilyasfoo** [comment]
Hi, @hsingyuc! Can you help to remove the changes made to `readme.txt` and add a changelog by running `npm run changelogger add` instead? After that, I should be able to merge it.

**Comment by hsingyuc** [comment]
@ilyasfoo  I added changelog entry.

**Comment by ilyasfoo** [comment]
Thank you, @hsingyuc! Unfortunately, there seem to be conflicts. Also, now that `2.7.0` is in beta, I think it's best to move the database changes to target `2.8.0`.

Thank you so much for your patience on this one

**Comment by hsingyuc** [comment]
@ilyasfoo  no problem at all, I just rebased it.

**Comment by ilyasfoo** [comment]
@hsingyuc Ah, now unit tests seems to be failing. Appreciate it if you can also help to fix that 🙏

**Comment by hsingyuc** [comment]
@ilyasfoo  Could you check if the changes I just made causing E2E test failure?  I have 'phpunit' failed to build error and am unsure how to fix it so that I couldn't test it.

**Comment by ilyasfoo** [comment]
@hsingyuc It could be a sporadic failure. I've re-ran and it passed. Merging it now
