### PR TITLE
Fix datepicker in advanced filter

### LINKED ISSUE #7507: Customer Search Advanced Filters Custom Date Range Returning Blank Result
### Describe the bug

When you navigate to WooCommerce > Customers and try to use the "Advanced Filters"  to filter "Registered" or "Last Active" customers by a date range, you get a blank result if you try to move to a month in the past or in the future using the calendar Prev/Next arrow.

Screencast: https://d.pr/i/DnTiuP

### To Reproduce

1. Go to WooCommerce > Customers
2. In the "Show" data field select "Advanced Filters"
3. Click "Add a filter" and select "Registered" or "Last Active"
4. Click the calendar field to open the calendar 
5. Click on the Next/Prev icon of the calendar and you'll get a blank result. 

### Actual behavior:

The calendar prev/next arrow returns a blank result

### Screenshots
https://d.pr/i/DnTiuP

### Expected behavior

Calendar prev/next icon should show the previous or next month. 

### Desktop (please complete the following information):

* OS: MacOS Bigsur
* Browser: Google Chrome
* Version 11.4

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #7507 

Make sure we set the onMonthPreviewed prop as this is required for wp.components.DatePicker

### Screenshots

date-filter

### Detailed test instructions:

1. Go to WooCommerce > Customers
2. In the "Show" data field select "Advanced Filters"
3. Click "Add a filter" and select "Registered" or "Last Active"
4. Click the calendar field to open the calendar 
5. Click on the Next/Prev icon of the calendar it should switch months correctly

### CODE REVIEW

File: packages/components/src/calendar/date-picker.js [hunk 1]
```diff
@@ -127,6 +127,8 @@ class DatePicker extends Component {
 									this.onDateChange,
 									onToggle
 								) }
+								// onMonthPreviewed is required to prevent a React error from happening.
+								onMonthPreviewed={ noop }
```
Comment (louwie17) [inline packages/components/src/calendar/date-picker.js:131]: `onMonthPreviewed` is a required prop, as you can see by it's use in DateTimePicker, not sure why it doesn't default to `noop` in it's own component:
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/date-time/index.js#L29

**Review by joshuatf — APPROVED** [review]
Testing well and LGTM!  🚢 

FWIW, tested with the latest GB and this problem does not exist, so it seems like it may have already been addressed, but good to get it working in WCA in the meantime.

**Comment by joshuatf** [comment]
Do we want to cherry pick this one?

**Comment by louwie17** [comment]
> Do we want to cherry pick this one?

Probably wouldn't be a bad idea, given the fix is very minimal and it will make some users happy if it gets in earlier.
cc: @joelclimbsthings
