### PR TITLE
Fix/7548 set up marketing tools title

### LINKED ISSUE #7548: [GlobalStep] "Set up marketing tools" screen title is displayed as "Home".
## Bug Description:
"Set up marketing tools" screen title is displayed as "Home".

## Environment:
Woocommerce Version : WooCommerce 5.7.0 Beta-1
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the setup wizard.
1. Go to "WooCommerce -> Home"
1. Click on "Set up marketing tools" option.
1. Observe that "Home" as header displayed for "Set up marketing tools" screen.

## Actual Result:
"Set up marketing tools" screen title is displayed as "Home".

## Expected Result:
It should display respective screen title for "Set up marketing tools" option.

## Screenshot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 5.7.0
REST API Version: ✔ 5.7.0
WC Blocks Version: ✔ 5.7.0
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.0-rc.2
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.22
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.0
WC Database Prefix: wp_
Total Database Size: 6.82MB
Database Data Size: 5.01MB
Database Index Size: 1.81MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.50MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
page: 7
post: 2
product: 24
product_variation: 10
shop_coupon: 1
shop_order: 20
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Google Listings and Ads: by WooCommerce – 1.4.1
Jetpack: by Automattic – 10.0
Mailchimp for WooCommerce: by Mailchimp – 2.5.2
WooCommerce: by Automattic – 5.7.0-beta.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 113
Oldest: 2021-08-23 07:18:32 +0000
Newest: 2021-08-23 13:56:42 +0000

### Status report information ###

Generated at: 2021-08-23 15:06:02 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by jacob-sewell**
Fixes #7548 

For the "Set up marketing tools" task page, there was no defined title in the Header component, so it went back to the default title of "Home".
Added a line for the "marketing" task.

### Screenshots
image

### Detailed test instructions:

- Go to "WooCommerce -> Home"
- Select "Set up markting tools" option
- Verify the header displays a sensible title

### CODE REVIEW

File: client/header/index.js [hunk 1]
```diff
@@ -70,6 +70,7 @@ const getPageTitle = ( defaultTitle ) => {
 			payments: __( 'Set up payments', 'woocommerce-admin' ),
 			tax: __( 'Add tax rates', 'woocommerce-admin' ),
 			appearance: __( 'Personalize your store', 'woocommerce-admin' ),
+			marketing: __( 'Set up marketing tools', 'woocommerce-admin' ),
```
Comment (joshuatf) [inline client/header/index.js:73]: I didn't even realize we were adding all task titles here.  This definitely makes me think we should be using `SlotFill` or some other means to encapsulate logic in their respective components.

This might be worth outlining an issue if you have time with the "cooldown" label so we can tackle this later.

**Review by joshuatf — APPROVED** [review]
Nice catch, @jacob-sewell!  Changes look good and pre-approving- can you remove the `package-lock.json` commit from this PR before merging?

File: client/header/index.js (hunk 1 above)
Comment (mattsherman) [reply client/header/index.js:73]: This definitely seems sub-par (existing issue, not a comment on this particular PR!) and should be addressed in the future!

**Comment by jacob-sewell** [comment]
The changelog linter is complaining about not having a changelog for "7640", which is the number of this PR. Should I have named by changelog file with the PR number instead of the issue number, or is there something else that's making this confused?

**Comment by joshuatf** [comment]
> Was that something that was supposed to be automagically done by the command line tool, and I just did things out of order? Or should I remember to add #{PR_NUMBER} at the end of all my changelog messages?

We have to manually add it right now, but also agree this could be done with a bit of magic.
