### PR TITLE
Fix sorting to push Storefront to the top of the theme list

### LINKED ISSUE #4185: Store Profiler - Theme step: Storefront not being displayed as the first option
**Describe the bug**
In the theme step we're not showing Storefront as the first option available and this can hurt the conversion rate of this step, considering that so far a low number of users chose a paid theme: https://d.pr/i/3AQ3of

**To Reproduce**

1. Install woocommerce-4.1.0-rc.1 and in the meantime don't install Storefront
2. Visit the theme selection step
3. See that Storefront isn't the first option available

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #4185 

Sorts themes so that Storefront is at the top again.

### Screenshots
Screen Shot 2020-04-23 at 8 54 15 PM

### Detailed test instructions:

1. Delete the `wc_onboarding_themes` transient.
1. Enable the profiler and visit the theme step.
1. Make sure Storefront is shown directly next to your active theme (or as your active theme if you're using Storefront).

### CODE REVIEW

File: tests/features/class-wc-tests-onboarding.php [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ */
+class WC_Tests_Onboarding extends WC_Unit_Test_Case {
+
+	/**
+	 * Tests that the themes returned from woocommerce.com are sorted properly.
+	 * - The first result should be the active theme.
+	 * - The second result should always be Storefront.
+	 */
+	public function test_get_themes_storefront_first() {
+		// TODO: Perhaps we should mock the call to the remote in get_themes to speed things up.
```
Comment (jeffstieler) [inline tests/features/class-wc-tests-onboarding.php:21]: Rather than call this whole method (with an HTTP request flying), how about we refactor the call to `usort()` with a new public static method on the `Onboarding` class that can be unit tested directly?

**Comment by timmyc** [comment]
Thanks for the feedback @jeffstieler and @psealock - I refactored a bit and changed the code to remove the HTTP request in the test suite. Ready for one last set of :eyes:

File: tests/features/class-wc-tests-onboarding.php [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+			'id'   => 2,
+			'slug' => 'chicken',
+		);
+		$theme3        = (object) array(
+			'id'   => 3,
+			'slug' => 'Storefront',
+		);
+		$theme4        = (object) array(
+			'id'   => 4,
+			'slug' => 'poutine',
```
Comment (jeffstieler) [inline tests/features/class-wc-tests-onboarding.php:33]: The theme is "Timmy's hungry". 😆

File: src/Features/Onboarding.php [hunk 3]
```diff
@@ -281,16 +300,8 @@ public static function get_themes() {
...
-					$theme_data->products,
-					function ( $product_1, $product_2 ) {
-						if ( 'Storefront' === $product_1->slug ) {
-							return -1;
-						}
-						return $product_1->id < $product_2->id ? 1 : -1;
-					}
-				);
+				$theme_data           = json_decode( $theme_data['body'] );
+				$theme_data->products = self::sort_woocommerce_themes( $theme_data->products );
```
Comment (jeffstieler) [inline src/Features/Onboarding.php:304]: We should check for the `products` property first, eh?

Nitpick - no need to overwrite this property. Could just use a new variable.

File: src/Features/Onboarding.php [hunk 4]
```diff
@@ -269,6 +269,25 @@ public static function get_allowed_product_types() {
...
+	 * Sort themes returned from WooCommerce.com
+	 *
+	 * @param  array $themes Array of themes from WooCommerce.com.
+	 * @return array
+	 */
+	public static function sort_woocommerce_themes( $themes ) {
+		usort(
+			$themes,
+			function ( $product_1, $product_2 ) {
+				if ( in_array( 'Storefront', array( $product_1->slug, $product_2->slug ), true ) ) {
```
Comment (jeffstieler) [inline src/Features/Onboarding.php:282]: We should check for the `slug` properties first.

File: src/Features/Onboarding.php [hunk 5]
```diff
@@ -269,6 +269,25 @@ public static function get_allowed_product_types() {
...
+					return 'Storefront' === $product_1->slug ? -1 : 1;
+				}
+				return $product_1->id < $product_2->id ? 1 : -1;
```
Comment (jeffstieler) [inline src/Features/Onboarding.php:285]: Same goes for `id`.
