### PR TITLE
Publish storybook docs, remove react docgen based docs

### LINKED ISSUE #6098: Cannot update the component docs
**Describe the bug**
I tried to update the docs, by updating JSDocs of a component's prop, then running `npm run docs`, but nothing changed.

**To Reproduce**

1. Change the line https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/date-range-filter-picker/index.js#L178 to ` * Foo`
2. Run `npm run docs`
3. Check https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/date-range-filter-picker/index.js#L178

**Expected behavior**
The description should be changed to "Foo"
```
`onRangeSelect` | Function | `null` | Foo
```

**Additional context**
It seems that `generate-docs` has a check for that specifically https://github.com/woocommerce/woocommerce-admin/blob/main/bin/generate-docs/index.js#L102:L102
So it does not update the docs on purpose, but why?

Removing this particular check resulted in an even worse result with old docs concatenated with malformed new ones.

How can I update generate updated docs?

(I hope the answer is not: "Do it manually here and there". Except for the redundant, manual labor, it is so bug-prone, and a short way to get the docs out of sync & date.)

### PR DESCRIPTION
**Pull request by samueljseay**
Fixes #6098 

I've done a few things here:

1. Remove react docgen based docs
2. Update the storybook setup to work better with our webpack build so that a static storybook can be built
3. Embed the storybook via an iframe in the docsify docs. This is an interim solution, later it may make more sense to host storybook separately.
4. Add a gh pages deploy action that will deploy static storybook to gh pages branch (for now we'll test on a testing branch)
5. Add a story with args support to make sure that works (see the Badge component)
6. Update a few dependencies - notably: get rid of node-sass (deprecated) in favor of dart sass.

**NOTE** Storybook still needs more work, quite a few components still don't look right due to their reliance on styles in wp-admin. I'll try tackle this separately. I think also since Gutenberg is moving towards css-in-js we could also move that way with these components and then we won't have troubles like this in future anyway. I don't think I've made any existing components display worse here. But its good to see more recent components like Badge and ExperimentalList displaying correctly without dependence on Wordpress.

Also I think the existing docsify docs are a bit out of date and incomplete too. Out of scope to fix that here but its on my list.

### Screenshots

Screenshot 2021-05-26 at 3 53 08 PM

### Detailed test instructions:

There are 2 things worth testing:

* Running the local docs: `npm run storybook`
* Generate the static docs: `npm run docs && npx docsify serve` (Go to the `Components` menu item on the docsify docs)

### CODE REVIEW

File: packages/components/src/animation-slider/stories/index.js [hunk 1]
```diff
@@ -1,12 +1,16 @@
 /**
  * External dependencies
  */
-import { AnimationSlider } from '@woocommerce/components';
 import { Component } from '@wordpress/element';
 
+/**
+ * Internal dependencies
+ */
+import AnimationSlider from '../';
```
Comment (samueljseay) [inline packages/components/src/animation-slider/stories/index.js:9]: It makes more sense for stories to import directly from inside the package.

File: packages/components/src/badge/index.tsx [hunk 2]
```diff
@@ -0,0 +1,15 @@
+export type BadgeProps = {
+	count: number;
+} & React.HTMLAttributes< HTMLSpanElement >;
+
+export const Badge: React.FC< BadgeProps > = ( {
```
Comment (samueljseay) [inline packages/components/src/badge/index.tsx:5]: It was very simple to convert this component to TS and I thought it would be good to have a working example of TS + the storybook args feature.

File: packages/components/src/badge/stories/index.tsx [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+		<CardBody>
+			<Badge { ...args } />
+		</CardBody>
+	</Card>
+);
+
+export const Primary = Template.bind( {} );
+
+Primary.args = {
+	count: 15,
```
Comment (samueljseay) [inline packages/components/src/badge/stories/index.tsx:23]: This and the template satisfy storybooks args feature letting you interactively change the args passed to the component. A good follow up PR will be to convert more of the stories to support this feature.

File: packages/experimental/src/experimental-list/experimental-list.tsx [hunk 4]
```diff
@@ -18,14 +18,14 @@ export type ListProps = {
 
 export const ExperimentalList: React.FC< ListProps > = ( {
 	children,
-	listType = 'ul',
```
Comment (samueljseay) [inline packages/experimental/src/experimental-list/experimental-list.tsx:21]: This change looks random, but when using args with experimental list, it gives "undefined" as a possible prop value, if you choose that it crashes the component currently, by falling back to `ul` later it means if someone passed a falsy value the component won't crash

File: storybook/preview.js [hunk 5]
```diff
@@ -8,7 +8,23 @@ import { addDecorator } from '@storybook/react';
 /**
  * Internal dependencies
  */
-import './wordpress/css/wp-admin.min.css';
+
+import './wordpress/css/common.min.css';
```
Comment (samueljseay) [inline storybook/preview.js:12]: Manually doing these imports now because we need to import them statically when generating the static storybook we deploy to gh pages.

**Comment by samueljseay** [comment]
I've tested the deployed gh pages branch locally and it seems to work ok, but my plan is to test it manually by switching the repo's gh pages branch over temporarily and testing if they work before switching back to the current branch. If it works we can change the gh action script to point to the real gh page branch after merge.

**Review by louwie17 — COMMENTED** [review]
Thanks for working on this, this tested well and changes look great! I just have a couple small notes before stamping an approval.
For the `npx docsify serve`:
- Given you removed the documentation.md, did you also want to remove it from the sidebar: https://github.com/woocommerce/woocommerce-admin/blob/main/docs/_sidebar.md
- The features path gives a 404 when clicking on it in the sidebar, I believe because it needs a  `README.md` in the features folder, I assume you can just mimic the one from the examples folder.

I left one small note in the experimental list story

File: packages/experimental/src/experimental-list/stories/index.tsx [hunk 6]
```diff
@@ -2,19 +2,40 @@
...
+		<ListItem onClick={ () => {} }>
+			<div>Any markup can go here.</div>
+		</ListItem>
+		<ListItem onClick={ () => {} }>
+			<div>Any markup can go here.</div>
+		</ListItem>
+	</List>
+);
+
+export const Primary = Template.bind( { onClick: () => {} } );
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply packages/experimental/src/experimental-list/stories/index.tsx:36]: Yeah, this is the "args" format. Notice the Template takes a prop called `args`. Storybook infers it and lets you adjust the arguments live in the storybook and re-render but it has to be in this format.

[the remark this answers is not in the document]
Comment (samueljseay) [reply packages/experimental/src/experimental-list/stories/index.tsx:36]: We could probably remove the Default story though, happy to do that

**Comment by samueljseay** [comment]
> Given you removed the documentation.md, did you also want to remove it from the sidebar: https://github.com/woocommerce/woocommerce-admin/blob/main/docs/_sidebar.md

> The features path gives a 404 when clicking on it in the sidebar, I believe because it needs a README.md in the features folder, I assume you can just mimic the one from the examples folder.

Thanks for catching those! I'll fix that up.

File: packages/experimental/src/experimental-list/stories/index.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (samueljseay) [reply packages/experimental/src/experimental-list/stories/index.tsx:36]: Fixed https://github.com/woocommerce/woocommerce-admin/pull/7055/commits/c918158c4f63eb0b34b4e913ad1bf9d47e5547c9

**Comment by samueljseay** [comment]
@louwie17 Fixed your suggestions, thanks they definitely improved things.

Could you have another look when you get a chance? 🙇

File: README.md [hunk 7]
```diff
@@ -61,6 +61,35 @@ Run a single test by adding the path to the file name:
...
+cd docs
+npx docsify serve
+```
+
+When deployed the docsify docs also host an embedded version of the storybook docs. To generate that and test it locally in docsify you'll need to run:
+
+```
+npm install
+npm run docs
+npx docsify serve
```
Comment (louwie17) [inline README.md:81]: Just add a `cd docs` above `docsify serve` similar as above.

**Review by louwie17 — APPROVED** [review]
Looks good @samueljseay, thanks for the updates 👍 
I left one small readme update, and don't forget to update the `gh-pages.yml` action (unless you wanted to keep that pointing to the test branch?
Otherwise ready to 🚢

File: README.md (hunk 7 above)
Comment (samueljseay) [reply README.md:81]: good point thanks for this suggestion!
