### PR TITLE
Stop using missing installPlugin function and fix WCS 1.24 compatibility

### LINKED ISSUE #5024: WC Ship Order Page Prompt JS error
**Describe the bug**
WC Ship install prompt on order edit page does not work and generates a JS error.

**To Reproduce**

1. Create store **without** WCS installed
1. Set up store for order page prompt to install:
    a. WCS **not** installed
    b. U.S. Based
    c. No extra shipping extensions installed (e.g. 'UPS' live rates)
    d. Add shippable product
1. Create order for shippable product
1. Go to order edit page
1. See shipping banner
1. Click "Create shipping label"
1. See error
 

**Expected behavior**
WC Ship label prompt should open after WCS is installed/activated/loaded.

**Screenshots**
When the "create shipping label" button is pressed, it stays in the loading state forever:
image

And a JS error is generated:
image

### PR DESCRIPTION
**Pull request by c-shultz**
Fixes #5024 

- Updates WC Ship prompt to use `installPlugins` instead of `installPlugin`. This is necessary because somewhere along the way, `installPlugin` was removed
- Updates WC Ship prompt for compatibility with WCS 1.24.x. WCS 1.24.0 added some code splitting and data pre-loading, so the prompt setup steps need to be adjusted for compatibility.

### Screenshots
image

### Detailed test instructions:

1. Create store **without** WCS installed
1. Set up store for order page prompt to install:
    a. WCS **not** installed
    b. U.S. Based
    c. No extra shipping extensions installed (e.g. 'UPS' live rates)
    d. Add shippable product
1. Create order for shippable product
1. Go to order edit page
1. See shipping banner
1. Click "Create shipping label" and wait
1. JS error in #5024 should not appear
1. After installing/activating WCS finishes, **you should expect to see this new error** (instead of the old error):
image
1. Refresh page, and then you should see the that WCS has been installed and can be used:
image

There's an outstanding issue with WCS (https://github.com/Automattic/woocommerce-services/issues/2154) that prevents the immediate loading/launching of the shipping label modal. Once a fix for this is released, the full flow should work.

### Changelog Note:

Fix: Admin order page shipping label prompt compatibility with WCS 1.24.

### CODE REVIEW

File: src/Features/ShippingLabelBanner.php [hunk 1]
```diff
@@ -107,9 +107,9 @@ public function add_meta_boxes( $post_type, $post ) {
 				'normal',
 				'high',
 				array(
-					'context'               => 'shipping_label',
-					'order_id'              => $post->ID,
-					'shippable_items_count' => $this->count_shippable_items( $order ),
+					'context' => 'shipping_label',
+					'order'   => $post->ID,
+					'items'   => $this->count_shippable_items( $order ),
```
Comment (harriswong) [inline src/Features/ShippingLabelBanner.php:112]: @c-shultz I am trying to understand this part but I can't find reference to `shippable_items_count` in WCS. Is this something to do with code splitting? Or is it because of the key change here https://github.com/woocommerce/woocommerce-admin/pull/5025/files#r474927056?

**Comment by jonathansadowski** [comment]
Hi @c-shultz. Would it be possible to include this in the 1.5 milestone? We'd love to get this fix into WC 4.5. /cc @becdetat

File: client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js [hunk 2]
```diff
@@ -181,7 +189,7 @@ export class ShippingBanner extends Component {
 			'woocommerce-order-label',
 			__( 'Shipping Label', 'woocommerce-admin' ),
 			{
-				orderId,
+				order: { id: orderId },
```
[the remark this answers is not in the document]
Comment (c-shultz) [reply client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js:192]: This is because `orderId` was changed to `order` here: https://github.com/Automattic/woocommerce-services/pull/1995/files#diff-9efbb862e5edf64ea2f2d1c20fd3632e

**Comment by c-shultz** [comment]
@jonathansadowski, that would be great. What's the timing of that milestone?

**Comment by c-shultz** [comment]
Thanks to @harriswong for testing it out and discovering that it wasn't working with the production version (`npm run build`) of WCS. The latest changes account for the dev/production handling of the woocommerce-services-x.xx.x.css file and retrieve a promise from WCS for the data store so it can wait for it to resolve before using it. This fixes compatibility with the code splitting and dynamic loading functionality that was released in WCS 1.24.

File: client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js [hunk 3]
```diff
@@ -216,22 +224,26 @@ export class ShippingBanner extends Component {
...
-				const head = document.getElementsByTagName( 'head' )[ 0 ];
-				const link = document.createElement( 'link' );
-				link.rel = 'stylesheet';
-				link.type = 'text/css';
-				link.href = styles;
-				link.media = 'all';
-				link.onload = resolve;
-				link.onerror = reject;
-				head.appendChild( link );
+				if ( stylePath !== '' ) {
```
Comment (c-shultz) [inline client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js:234]: Only load stylesheet if it's available. This handles the case where WCS is a development build and therefore does not required or build the stylesheet (it is automatically loaded in that case)

**Comment by becdetat** [comment]
Hi @c-shultz :-)

I'm testing this out on a JN site and can't get the banner to appear. I'm going to DM you the details of the test site. Can you tell me what I need to do to get this working?

**Comment by jonathansadowski** [comment]
> @jonathansadowski, that would be great. What's the timing of that milestone?

WooCommerce Admin 1.5 Release is scheduled for Sept 7 (pbIJXs-gm-p2). [WooCommerce 4.5](https://developer.woocommerce.com/2020/08/21/woocommerce-4-5-0-beta-1/) is scheduled for Sept 8.

Sorry, my question may have been better aimed at @becdetat :)

Bec, are you okay with cherry-picking this fix into 1.5 after it's merged and then releasing another RC?

**Comment by c-shultz** [comment]
@becdetat, we're ready to merge on our end. Were you going to do any more testing/reviewing? I'll pre-emptively mark this for cherry-picking, as it would be great to get this in 4.5, if possible.

**Comment by becdetat** [comment]
It may be an issue with my JN site or how I'm building the wc-admin test zip, but I still get the original error with this - `TypeError: Cannot read property 'apply' of undefined`. It looks like everyone else is getting good results though so I'm happy to cherry-pick this into our 1.5.0-rc.2 release early next week.
