### PR TITLE
Improve hidden tab suppression/fix rapid requests

### LINKED ISSUE #2365: Endless requests breaking sites
This is a copy of an issue logged in WooCommerce, https://github.com/woocommerce/woocommerce/issues/23868.

>While adding products in after the update, I started having issues with my server maxing out the entry processes. I went to the logs to see what was happening. I discovered that there were some endpoints that were being repeatedly hit thousands of times until the server resources were expended. Here are the urls that were called over and over and over.

>GET /wp-json/wc/v4/admin/notes?page=1&per_page=25&status=unactioned&type=error%2Cupdate&_locale=user

>GET /wp-json/wp/v2/users/me?context=edit&_locale=user

>GET /wp-json/wc/v4/admin/notes?order=desc&orderby=date&page=1&per_page=1&type=info%2Cwarning&_locale=user

>GET /wp-json/wc/v4/products?low_in_stock=true&page=1&per_page=1&status=publish&_locale=user

>GET /wp-json/wc/v4/reports/orders?page=1&per_page=0&status_is%5B0%5D=processing&status_is%5B1%5D=on-hold&_locale=user

>GET /wp-json/wc/v4/admin/notes?page=1&per_page=25&status=unactioned&type=error%2Cupdate&_locale=user HTTP/1.1" 200 1064

cc @BodyStatements

### PR DESCRIPTION
**Pull request by coderkevin**
Fixes #2365 

This replaces the code from #1732 and later additions to it. I am also proposing this fix instead of #2377.

This fixes the rapid request problem that was happening when switching
tabs while having timed out requests. It changes the approach from
suppressing the actions sent out to preventing the read function from
being called at all.

I think the original problem has occurred because the original approach
was relying on an internal implementation of `apiFetch` from `wp.data`. This
new approach does not have such a dependency. It prevents apiFetch from
even being called. However, in the process, it will also prevent any
newly required resources from being fetched if the user manages to
switch tabs before it is requested. (e.g. refresh, then switch tabs
quickly).

_Replace this with a good description of your changes & reasoning._

### Detailed test instructions:

- Follow instructions on #2365 to test.
- Monitor requests in console. Switch tabs and observe requests rapid firing
- Check out this branch
- Follow instructions on #2365 and above to switch tabs and observe that no requests are sent when tab is not active.

### Changelog Note:

Fix rapid request issue when tab is not active.

### CODE REVIEW

File: client/wc-api/wp-data-store/create-api-client.js [hunk 1]
```diff
@@ -19,11 +19,6 @@ function createStore( name ) {
 function createDataHandlers( store ) {
 	return {
 		dataRequested: resourceNames => {
-			const { resources } = store.getState();
-			const newResources = resourceNames.some( resourceName => ! resources[ resourceName ] );
-			if ( ! newResources && document.hidden ) {
```
Comment (Aljullu) [inline client/wc-api/wp-data-store/create-api-client.js]: After removing this, I see `FRESH_DATA_REQUESTED` is being dispatched even when the tab is inactive. That means we update the [`lastRequested`](https://github.com/woocommerce/woocommerce-admin/blob/master/client/wc-api/wp-data-store/reducer.js#L26) value even though no request is made.

That's an issue in the following scenario. Imagine I have two tabs open and WooCommerce Admin is an inactive tab. If I reload it without activating, `FRESH_DATA_REQUESTED` is dispatched (so `lastRequested` updated). Then, switching to WooCommerce Admin will show no data and it will not update it until it timeouts:
Peek 2019-06-11 10-58

Can you reproduce that too?

Comment (jeffstieler) [reply client/wc-api/wp-data-store/create-api-client.js]: I'm able to reproduce this @Aljullu.

Comment (jeffstieler) [reply client/wc-api/wp-data-store/create-api-client.js]: Adding this back in resolved for me:

```javascript
if ( document.hidden ) {
    return;
}
```

Comment (coderkevin) [reply client/wc-api/wp-data-store/create-api-client.js]: That makes sense. I'll see what I can do to adjust this.

Ultimately, I think this will be a temporary fix. I'm working on an update to fresh-data now and I can incorporate a better fix within that.

Comment (psealock) [reply client/wc-api/wp-data-store/create-api-client.js]: Can we add this temporarily with a comment? It would be nice to get this out asap in `0.13.0` today or tomorrow.

Comment (jeffstieler) [reply client/wc-api/wp-data-store/create-api-client.js]: Done in 26cf428.

Comment (psealock) [reply client/wc-api/wp-data-store/create-api-client.js]: I confirmed this solves the issue. As soon as you switch to activate the wc-admin page, a request is made.
