### PR TITLE
Fix some data not to being imported when 'skip_existing' option is enabled

### LINKED ISSUE #2343: If 'skip_existing' is set to true, not all customers are imported
I have a store with 160 customers. When importing all historical data (after having deleted it before) with the option `skip_existing` to true, it only imports 85 of them.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #2343.

When `skip_existing` was set to true, in every batch the table of customers/orders to import was getting smaller (because recently imported customers/orders were not included) but we were still increasing the `offset` in each query. That made last batches to import nothing.

Making sure `offset` is always `0` when `skip_existing` is true, fixes the issue.

### Detailed test instructions:

I found it easier to work on this merging the branch from #2312. That way, you get progress bars in the import tool and you can see how many customers/orders are imported every time.

- Go to _Analytics_ > _Settings_.
- Click on _Delete Previously Imported Data_ and make sure all tasks run.
- Then, start an import making sure you have _Skip previously imported customers and orders_ selected.
- Verify it imports all customers and all orders.

### CODE REVIEW

File: includes/class-wc-admin-reports-sync.php [hunk 1]
```diff
@@ -571,6 +572,7 @@ public static function get_user_ids_for_batch( $days, $skip_existing, $query_arg
 		}
 
 		if ( $skip_existing ) {
+			$query_args['paged'] = 1;
```
Comment (jeffstieler) [inline includes/class-wc-admin-reports-sync.php]: What do you think about moving this to https://github.com/woocommerce/woocommerce-admin/blob/fc20a2f2b18b44e9d87e139e5127874b9ac0da43/includes/class-wc-admin-reports-sync.php#L664 ?

Comment (Aljullu) [reply includes/class-wc-admin-reports-sync.php]: Sounds good, changed in 93ebea7f92d615b9d025f019850207ab4abc9c39. I also added an explanatory comment.

**Comment by psealock** [comment]
I'll merge this one to get it into `0.13.0` since its been tested and added comments looking good.
