### PR TITLE
Address revenue discrepancies

### LINKED ISSUE #2855: Net Revenue numbers don't match
**Describe the bug**
The Net Revenue total on the Revenue page and the Orders page match, however they do not match the Net Revenue on the Product page or the Net Revenue on the Categories page. However the Product and Category page Net revenues match each other.

Woo Admin 1.8.1
Woo 3.7.0

**To Reproduce**
Run the analytics reports

**Expected behavior**
If these are representing Net revenue the total should be the same in all reports, if they are not calculating the same way they need to be labeled in a way that represents what is actually calculated.

**Screenshots**
If applicable, add screenshots to help explain your proble
Revenue Net Discrepencies

**Desktop (please complete the following information):**

* OS: iOS 
* Browser Firefox
* Version Latest

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #2855
See #2918

This PR addresses the revenue discrepancies between Product and Order revenue totals. Categories use Product totals and Revenue uses Order totals.

This PR makes the following changes:
- Re-label the product revenue total on the Product/Categories screens to `Net Product Revenue`

Product revenue does not include coupons, fees, or partial refunds (existing stores may have flat amount refunds not applied to products). If we were to include these amounts in the report total, then the sum of net revenue in the table would not sum to the totals in the header/footer. 

- Exclude `wc-auto-draft` orders from import

The amounts on these orders were being included in the product revenue but excluded from the order revenue.

- Round product line item total amounts on product lookup for tax inclusive pricing. If WC is configured to round tax on the line item, then the tax is also rounded.

This change only affects sites that have tax inclusive pricing. With tax inclusive pricing the line items totals on the order contain unrounded currency fractions. It only takes a few of these to produce a total discrepancy.

### Detailed test instructions:

- On `master`
- Set WC to tax inclusive pricing
- Set a tax rate of 11% or more
- Use `wc-smooth-generator` to generate 10-20 orders
- Add a partial refund to one of the orders
- Create a manual order and apply a fixed amount coupon
- Create a second order and set the product price to 1/2 of the regular price when adding the line item (for #2918)
- Run the jobs to import the orders
- Load the Product & Order Analytics for today, note discrepancies
- Switch to this PR
- Re-import your data with Skip existing unchecked
- Compare Product & Order Analytics for today

### Changelog Note:

Fix: Address discrepancies in Revenue totals between Analytics screens.

### CODE REVIEW

**Comment by LevinMedia** [comment]
Thanks so much for working through this @rrennick! 

I tested on my end, and I'm now seeing the correct net numbers in the product and category reports! 

My only request would be that you change the label from `net product revenue` to `Net Sales`. 

I've got a [branch](https://github.com/woocommerce/woocommerce-admin/compare/update/change-revenue-to-sales) in the works that will update the labels on all the things, as well as fix the gross, and refund calculations in the revenue report. I'll open a PR for it later today / tonight.

File: src/API/Reports/Products/DataStore.php [hunk 1]
```diff
@@ -402,6 +402,8 @@ public static function sync_order_products( $order_id ) {
 
 		$order_items = $order->get_items();
 		$num_updated = 0;
+		$decimals    = wc_get_price_decimals();
+		$round_tax   = 'no' === get_option( 'woocommerce_tax_round_at_subtotal' );
```
Comment (joshuatf) [inline src/API/Reports/Products/DataStore.php]: Nice!  I'm wondering if it's worth keeping a list somewhere of all the settings that might affect our data and require re-syncing.

Not something that has to be handled here, but long-term it might be nice to know what requires a re-sync.

Comment (rrennick) [reply src/API/Reports/Products/DataStore.php]: Good idea. Created #3108 .
