### PR TITLE
Remove updated stock products from Activity Panel

### LINKED ISSUE #2175: After Updating Stock - Product Still Remains in Stock Panel
**Describe the bug**
When updating a product that is either out of stock, or below the low stock inventory threshold to a level that is above the low-stock threshold - the product still appears in the Stock Panel until you refresh the page.

**To Reproduce**

1. Set your low stock threshold to 2
2. Edit a product so the stock level is 1
3. Visit the dashboard, note the indicator is shown for the Stock Panel
4. Expand the panel, then modify the stock of the product you updated in step 2 to a number greater than the low stock threshold
5. Note the product is still shown after updating the stock to a value greater than the low stock threshold

**Expected behavior**
After updating inventory to a level above the low stock threshold, I anticipated the product to no longer be shown. The product is no longer shown after you refresh the page.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #2175.

### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [x] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots
Screenshot_2019-06-17 Stock ‹ Analytics ‹ WooCommerce — WooCommerce

### Detailed test instructions:
- Make sure you have some products in 'low stock'.
- Open the _Stock_ tab of the Activity Panel.
- Modify the stock of one of the products so it's no longer in 'low stock'.
- Verify the opacity of the product card is reduced but the card is still visible.
- Close the panel and open it again.
- Verify the card disappeared.

### CODE REVIEW

File: client/header/activity-panel/panels/stock/card.js [hunk 1]
```diff
@@ -117,6 +135,17 @@ class ProductStockCard extends Component {
 
 	render() {
 		const { product } = this.props;
+		const { edited, editing } = this.state;
+		const { notifyLowStockAmount } = wcSettings;
+		const lowStockAmount = Number.isFinite( product.low_stock_amount )
+			? product.low_stock_amount
+			: notifyLowStockAmount;
+		const isLowStock = product.stock_quantity < lowStockAmount;
```
Comment (jeffstieler) [inline client/header/activity-panel/panels/stock/card.js]: Should this be `<=` to match https://github.com/woocommerce/woocommerce/blob/a247e08ad0b0fa93b8ece6ecd48b7b4d7ec432db/includes/admin/class-wc-admin-dashboard.php#L221 ?

Comment (Aljullu) [reply client/header/activity-panel/panels/stock/card.js]: Good catch! Fixed in 682fe11c269403652397d51779c9dcc993503422.

File: client/header/activity-panel/panels/stock/card.js [hunk 2]
```diff
@@ -117,6 +135,17 @@ class ProductStockCard extends Component {
...
+
+		if ( ! isLowStock && ! edited && ! editing ) {
```
Comment (jeffstieler) [inline client/header/activity-panel/panels/stock/card.js]: It looks like this is the logic to hide the card once the stock has been updated and the panel closed/reopened. Can you add a comment to explain that?

File: client/wc-api/items/mutations.js [hunk 3]
```diff
@@ -5,9 +5,14 @@
  */
 import { getResourceName } from '../utils';
 
-const updateItem = operations => ( type, id, itemData ) => {
+const updateItem = operations => async ( type, id, itemData, callback ) => {
```
Comment (jeffstieler) [inline client/wc-api/items/mutations.js]: What do you think about using Promises here instead of a callback argument?

**Comment by timmyc** [comment]
Is this ready for some more 👀 @Aljullu ?

File: client/header/activity-panel/panels/stock/card.js (hunk 2 above)
Comment (Aljullu) [reply client/header/activity-panel/panels/stock/card.js]: Added in 4536f027a1d26120827834e877e482ab1c02b5ee. :+1:

File: client/wc-api/items/mutations.js (hunk 3 above)
Comment (Aljullu) [reply client/wc-api/items/mutations.js]: I took a look at how Gutenberg deals with success/error messages for async actions and it looks like they add the notices directly from the action creator instead of the component (see [savePost](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/store/actions.js#L258) for example). So I opted for moving all the logic from the component to the mutation in b19643ed72715a045d9114123789d222933a0497, I would like to hear your thoughts on how it looks.

**Comment by Aljullu** [comment]
> Is this ready for some more eyes @Aljullu ?

Yes, I guess so. I was experimenting with integrating `@wordpress/data-controls` into our dependencies, but I guess there is no need to do it now and in this PR, so I think this can be reviewed right away. I updated the labels accordingly.

File: client/wc-api/items/mutations.js [hunk 4]
```diff
@@ -1,15 +1,47 @@
...
+	const oldStockQuantity = product.stock_quantity;
+	const resourceName = getResourceName( 'items-query-products-item', product.id );
+
+	// Optimistically update product stock
+	operations.updateLocally( [ resourceName ], {
+		[ resourceName ]: { ...product, stock_quantity: newStock },
+	} );
+
+	const result = await operations.update( [ resourceName ], {
+		[ resourceName ]: { id: product.id, stock_quantity: newStock },
```
Comment (psealock) [inline client/wc-api/items/mutations.js]: `type` and ` parent_id` need to be passed in here as well. There is a switch statement in `update` that requires it.

https://github.com/woocommerce/woocommerce-admin/blob/b19643ed72715a045d9114123789d222933a0497/client/wc-api/items/operations.js#L98-L106

File: client/header/activity-panel/panels/stock/card.js [hunk 5]
```diff
@@ -119,14 +124,27 @@ class ProductStockCard extends Component {
...
 	}
 
 	render() {
 		const { product } = this.props;
-		const { editing } = this.state;
+		const { edited, editing } = this.state;
+		const { notifyLowStockAmount } = wcSettings;
+		const lowStockAmount = Number.isFinite( product.low_stock_amount )
+			? product.low_stock_amount
+			: notifyLowStockAmount;
```
Comment (psealock) [inline client/header/activity-panel/panels/stock/card.js]: :+1:

File: client/wc-api/items/mutations.js (hunk 4 above)
Comment (Aljullu) [reply client/wc-api/items/mutations.js]: Oh, right I forgot that when refactoring :man_facepalming: , thanks for noticing!

It's fixed in 855587a72f9baca96d4f2c4210495b3d3ebb7884.

**Comment by Aljullu** [comment]
Thanks for taking a look @psealock! This is ready for another review.

**Comment by Aljullu** [comment]
Thanks for reviewing @psealock!

> Items that are low_in_stock aren't being returned by the `/products?low_in_stock=true` endpoint. Below, the Stock Report accurately labels Sunglasses and V-neck in Blue as `low`, but those products aren't being returned by the above endpoint, so I don't see them in the Stock panel.
> 
> Screen Shot 2019-06-27 at 12 20 05 PM
> 
> Can you reproduce this?

That's weird. I can't reproduce it but I think it's worth opening an issue for that, so we can investigate it further. There might be an inconsistency between `products` and `stock` endpoints and the way they calculate which products are in low stock.

I will merge this PR as-is since I think this issue is not related to the changes introduced here, and we can deal with it in a follow-up.
