### PR TITLE
Fix category lookup class

### LINKED ISSUE #7680: Trying to get property 'category_id' of non-object in CategoryLookup classs
There is a bug in update method in CategoryLookup class. 
Getting message 
`Trying to get property 'category_id' of non-object`

It seems line 191 should be 
`$inserts[] = $this->get_insert_sql( $child, $ancestor );`
instead of 
`$inserts[] = $this->get_insert_sql( $child->category_id, $ancestor );`

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #7680 

Fixes a warning that showed when changing the parent of a product category that has children. I added several PHP tests for this.
I am not as familiar with the `category_lookup` use cases, so I didn't find any direct area's where this could off broken functionality.

### Detailed test instructions:

- Revert the change locally in the `CategoryLookup.php` file and run `npm run test:php`
- Notice how tests fail with the error mentioned in #7680 
- Reset the `CategoryLookup.php` file to the changes made as part of this branch
- Run `npm run test:php` again, all tests should pass this time

To see the warning in a live environment:
- Load `main` and create a product category
- For the same category add some children product categories
- Now add a parent to the product category with the children (parent > parent > children)
- Load `debug.log` and notice the `Trying to get property 'category_id' of non-object` warning
- Load this branch and do the same thing, and notice how there are no warnings.

### CODE REVIEW

File: src/CategoryLookup.php [hunk 1]
```diff
@@ -179,16 +179,17 @@ protected function delete( $category_id, $category_tree_id ) {
 	protected function update( $category_id ) {
 		global $wpdb;
 
-		$ancestors = get_ancestors( $category_id, 'product_cat', 'taxonomy' );
-		$children  = get_term_children( $category_id, 'product_cat' );
-		$inserts   = array();
-		$inserts[] = $this->get_insert_sql( $category_id, $category_id );
+		$ancestors    = get_ancestors( $category_id, 'product_cat', 'taxonomy' );
+		$children     = get_term_children( $category_id, 'product_cat' );
```
Comment (louwie17) [inline src/CategoryLookup.php:183]: `get_term_children` returns an array of id's

**Review by mattsherman — APPROVED** [review]
Verified tests fail without fix. Thanks for adding the automated testing! Nice job.
